### ISSUE TITLE
'module' object has no attribute 'SIGCHLD'

### ISSUE THREAD

**Issue by alexwahl** [novnc/websockify#108]
Hi!
i tried to start the echo demo. Therfore i put the echo.py and websocket.py in one directory. when i try to start up i get this error:

  H:\workspace\python\websocketServer\src>python echo.py 9999
  WARNING: no 'resource' module, daemonizing is disabled
  Traceback (most recent call last):
    File "echo.py", line 74, in <module>
      server.start_server()
    File "H:\workspace\python\websocketServer\src\websocket.py", line 827, in star
  t_server

```
signal.SIGCHLD: signal.getsignal(signal.SIGCHLD),
```

  AttributeError: 'module' object has no attribute 'SIGCHLD'

Python version is 3.3.2

**Comment by joerg86** [comment]
Hi, 
I'm running into the same problem on windows. It seems that it was already fixed (see commit linked in this thread), but recently, websockify.py has changed a bit and signal.SIGCHLD is again expected to be there (which is not the case on windows). I have made a patch and will try to submit it as it seems that I cannot uploaded it here directly.

Jörg

**Comment by joerg86** [comment]
Sorry, I was wrong. The patch submitted by DirectXMan12 simply hasn't been merged into the master branch.  Why not?

**Comment by DirectXMan12** [comment]
@joerg86 Sorry about the delay (holidays).  IIRC, I was waiting for someone with Window to actually test my change to see if it worked.  I thought I posted it somewhere, but I can't seem to find the contents of the patch itself.  If you have a working patch, I'd be happy to look at it.  Just submit a pull request against the repository (and mention this bug commit message).

**Comment by jeremy-y12** [comment]
I applied the commit above (https://github.com/kanaka/websockify/commit/3ee9ff7f4d5b27c77c75e246d4ac8d642049b02f) and got a different error after trying to connect to the server:
````
D:\USER\Downloads\websockify-master>D:\Programs\PortablePython2.7.6.1\App\pyth
on.exe run 8088 localhost:30000
WARNING: no 'resource' module, daemonizing is disabled
WebSocket server settings:
  - Listen on :8088
  - Flash security policy server
  - No SSL/TLS support (no cert file)
  - proxying from :8088 to localhost:30000
Traceback (most recent call last):
  File "run", line 5, in <module>
    websockify.websocketproxy.websockify_init()
  File "D:\USER\Downloads\websockify-master\websockify\websocketproxy.py", lin
e 419, in websockify_init
    server.start_server()
  File "D:\USER\Downloads\websockify-master\websockify\websocket.py", line 101
8, in start_server
    self.msg("handler exception: %s", str(exc))
UnboundLocalError: local variable 'exc' referenced before assignment

D:\USER\Downloads\websockify-master>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Programs\PortablePython2.7.6.1\App\lib\multiprocessing\forking.py", l
ine 380, in main
    prepare(preparation_data)
  File "D:\Programs\PortablePython2.7.6.1\App\lib\multiprocessing\forking.py", l
ine 489, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named run
````

**Comment by mliudev** [comment]
Any updates on this? It looks to be working with the changes from the bug/108-no-sigchld-in-windows branch.

**Comment by floooh** [comment]
Bump. I'm currently running into the same problem on Windows (OSX works well). Is there a recommended way to make websockify work on Windows?

Thanks!

**Comment by samhed** [comment]
> Is there a recommended way to make websockify work on Windows?

I'm afraid not, I haven't seen anyone managing to get it working on Windows recently.

**Comment by totaam** [comment]
I had something that more or less worked OK on win32, based on the trunk code from a few months ago.
You need the SIGCHLD bits, those should be merged already as they're trivial and always needed on win32.
The much more difficult part is handling WSARESTART on the socket. I haven't tried it lately, so it may have broken again - it's very brittle, here are some pointers:
http://xpra.org/trac/ticket/1211

**Comment by ironmann250** [comment]
@jebej the warning that it can't find resource module is because it is named **rsrc** not resource so you can type **import rsrc as resource** in webscoket.py

**Comment by samfrances** [comment]
Still seeing this issue on windows. Any news?

**Comment by sebLopezCot** [comment]
After trying all fixes above, I was able to get it to run on Windows in python, but when a socket connects it complains about multiprocess. Meanwhile the Nodejs version of websockify works fine under Windows (see novnc/novnc#807).

**Comment by CendioOssman** [comment]
Fixed in ddcec961ec16aeec76e232684b89ea33ef3e0657. However many more issues on Windows remain. See #67.

**Comment by docdawning** [comment]
I've just tried Websockify 0.8.0 on Windows 10 and I run in to this too:
`websockify 9000 192.168.19.1:9000
WARNING: no 'resource' module, daemonizing is disabled
WebSocket server settings:
  - Listen on :9000
  - Flash security policy server
  - No SSL/TLS support (no cert file)
  - proxying from :9000 to 192.168.19.1:9000
Traceback (most recent call last):
  File "C:\Python27\Scripts\websockify-script.py", line 11, in <module>
    load_entry_point('websockify==0.8.0', 'console_scripts', 'websockify')()
  File "C:\Python27\lib\site-packages\websockify-0.8.0-py2.7.egg\websockify\websocketproxy.py", line 525, in websockify_init
    server.start_server()
  File "C:\Python27\lib\site-packages\websockify-0.8.0-py2.7.egg\websockify\websocket.py", line 986, in start_server
    signal.SIGCHLD: signal.getsignal(signal.SIGCHLD),
AttributeError: 'module' object has no attribute 'SIGCHLD'`

**Comment by wenchangshou2** [comment]
> I've just tried Websockify 0.8.0 on Windows 10 and I run in to this too:
> 
> ```
> websockify 9000 192.168.19.1:9000
> WARNING: no 'resource' module, daemonizing is disabled
> WebSocket server settings:
>   - Listen on :9000
>   - Flash security policy server
>   - No SSL/TLS support (no cert file)
>   - proxying from :9000 to 192.168.19.1:9000
> Traceback (most recent call last):
>   File "C:\Python27\Scripts\websockify-script.py", line 11, in <module>
>     load_entry_point('websockify==0.8.0', 'console_scripts', 'websockify')()
>   File "C:\Python27\lib\site-packages\websockify-0.8.0-py2.7.egg\websockify\websocketproxy.py", line 525, in websockify_init
>     server.start_server()
>   File "C:\Python27\lib\site-packages\websockify-0.8.0-py2.7.egg\websockify\websocket.py", line 986, in start_server
>     signal.SIGCHLD: signal.getsignal(signal.SIGCHLD),
> AttributeError: 'module' object has no attribute 'SIGCHLD'
> ```
> So I switched to the head revision of the repo, and got:
> 
> ```
> websockify 9000 192.168.19.1:9000
> WARNING: no 'resource' module, daemonizing is disabled
> Windows is not supported at this time
> ```
already settled?
