### ISSUE TITLE
handler exception: cannot serialize '_io.TextIOWrapper' object

### ISSUE THREAD

**Issue by Karankang007** [novnc/websockify#131]
I receive this error when running WebSockify with either --record or --verbose parameter.
This error is occuring because somehow the multiprocessing module is trying to serialize the file obj of logging library. 
![image](https://cloud.githubusercontent.com/assets/1234394/3392075/f23a7f0c-fcb0-11e3-8932-fcfac33d17f4.png)

**Comment by CendioOssman** [comment]
Duplicate of #67.
