### ISSUE TITLE
b64_ntop() / b64_pton() not universally available on all C libraries

### ISSUE THREAD

**Issue by maxnet** [novnc/websockify#165]
I am trying to cross-compile the C version of websockify for an embedded system that uses uclibc instead of glibc.
However it seems b64_ntop() / b64_pton() is not available with that.

```
websocket.o: In function `encode_hixie':
websocket.c:(.text+0x3f0): undefined reference to `b64_ntop'
websocket.o: In function `decode_hixie':
websocket.c:(.text+0x4e8): undefined reference to `b64_pton'
websocket.o: In function `encode_hybi':
websocket.c:(.text+0x614): undefined reference to `b64_ntop'
websocket.o: In function `decode_hybi':
websocket.c:(.text+0x86c): undefined reference to `b64_pton'
websocket.o: In function `do_handshake':
websocket.c:(.text+0x1224): undefined reference to `b64_ntop'
collect2: error: ld returned 1 exit status
```

Please consider bundling those methods locally with websockify.

**Comment by tg123** [comment]
maybe you can link those source code

https://github.com/lattera/glibc/blob/master/resolv/base64.c
or
http://www.opensource.apple.com/source/OpenSSH/OpenSSH-57.3/openssh/openbsd-compat/base64.c

**Comment by maxnet** [comment]
Can conform it compiles with the ISC base64.c code.

Still would be nice to have this fixed here, rather than me maintaining my own local patches, which is a pain to keep up-to-date with new versions.
