### ISSUE TITLE
_ssl.c:510: EOF occurred in violation of protocol on Safari Version 8.0.6 (10600.6.3) and IOS

### ISSUE THREAD

**Issue by rogaha** [novnc/websockify#182]
I see this message: `_ssl.c:510: EOF occurred in violation of protocol`

It doesn't work for Chrome and Safari on IOS as well.

**Comment by CendioOssman** [comment]
Wouldn't this be a Python bug rather than a websockify one?

**Comment by DirectXMan12** [comment]
closing due to age.
