### ISSUE TITLE
win32 support

### ISSUE THREAD

**Issue by kanaka** [novnc/websockify#2]
Add support for win32.

One of the main changes will require using the multiprocessing module rather than os.fork().

**Comment by alexchandel** [comment]
Python 2 was end-of-lifed on January 1.  Python 3.8 has complete Windows support for non-blocking TCP & UDP asyncio.  Convert websockify to use asyncio and it'll work natively on Windows.

**Comment by CendioOssman** [comment]
Windows support was fixed back in #388 so this should have been closed then.
