### ISSUE TITLE
handler exception: can't pickle <type 'thread.lock>

### ISSUE THREAD

**Issue by drt0927** [novnc/websockify#203]
-------python2.7 version exe
![image3](https://cloud.githubusercontent.com/assets/14919000/10329619/bbedc296-6cfe-11e5-8020-8fac4709c4f5.png)

-------python3.4 version exe
![image](https://cloud.githubusercontent.com/assets/14919000/10330114/12789604-6d04-11e5-9caa-660d3b95b830.png)

-------**init** add import
token_plugin, auth_plugin

![image](https://cloud.githubusercontent.com/assets/14919000/10354080/7abda356-6d97-11e5-95df-f05a11a09761.png)

How to fix?

thanks!

**Comment by rhtnmvp** [comment]
I want a web run.exe in Windows that supports multiprocessing .

**Comment by wolf427** [comment]
According to my experiment, windows do not support multiprocessing normally.So I find out where it was used and rewrite these lines as below:
                        elif multiprocessing:
                            self.vmsg('%s: new handler Process' % address[0])
                            #if __name__ == '__main__':
                            #p = multiprocessing.Process(
                            #        target=self.top_new_client,
                            #        args=(startsock, address))
                            #p.start()
                            self.top_new_client(startsock, address)
                            # child will not return
Remove the usage of multiprocessing and rebuild it. I'm not sure whether it will cause other problems, but now it works fine to me.

**Comment by CendioOssman** [comment]
It's part of the issues on #67. Closing as duplicate.
