### ISSUE TITLE
dump websocket traffic

### ISSUE THREAD

**Issue by famedoro** [novnc/websockify#224]
Hi,
I would like to know if there is a way to have the dump file of the traffic coming from a websocket.

This is my scenario:
I initially receive real time data from a website in a browser page,
I use the sniffer ( like this
http://www.freeproject.co.in/source/Network-Packet-Sniffer.aspx?pf=Java&t=web or
http://packetsnifferusingjpcap.blogspot.it/ which write on file all tcp/ip traffic
that passes through the network interface from a given ip address) in order to get data and send it to a my custom program .
Now my data provider supply the data using ssl (https) and websocket, then my sniffer doesn't receive
decrypted data in clear. To connect to my provider I must provide user, password and then in a
new page a temporarily generated key code, then the browser open a web page related to an
address xxx.yyy.nnn.zzz (without https prefix) which show realtime data.
Using wireshark and the instruction provided in
https://isc.sans.edu/forums/diary/Psst+Your+Browser+Knows+All+Your+Secrets/16415/
I'm able to decrypt ssl page.

This is a sample data decrypted using wireshark:

GET / HTTP/1.1
Host: serverpush.dot.it:7072
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: it,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: https://severdata.dot.it
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: 1VkXxdjYOBuOjfa+gAQ91A==
Cookie: _ga=GA1.2.458778788.1410278708; _gat=1; _gali=Avanti
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: fIKoaTEDrGcC8Qyxt5bppaevP9U=

...t...t.a.7...I...F...C...M...D...........F...................M...B...L.......~.......
RESULT=ACK
....5h..0m..s!..p:..q"...;...X.....8...=...~.B.}.3.|.G...^.......T.C.W.F.FP
..S..gR..w%..a&s...t...v...t...8...I...=...$...~.J.....C3DJI;0=16391.69;1=1.4877;4=104196873;20=2511792525067.33;7=21:52:35
.B.....;3SP500;0=1923.67;4=637246226;20=1677783824894.07;7=21:52:35
..L...N...L.......q...........
.......
...F...7...C...O......a...E...(...3...5...5....s..Cq..bs..
?...N...:...6......Y...{........... ... ...J.....DATA1I;0=16391.28;1=1.4851;4=104210258;20=2511792541458.61;7=21:52:36
.-.....&DATA2;4=637298282;20=1677783826817.68
.+.....$DATA2;0=1923.61;1=1.7632;7=21:52:36
..cq>.ar;.cQxU/%{N^BzV*R O3D.,@BxH04sU!R X)84........ ...N.Y.M.(.L..;.E.8.6.N.F.E.W.;._...J.....DATA1I;0=16389.91;1=1.4767;4=104222192;20=2511792557848.52;7=21:52:37
.K.....DATA2;0=1923.48;1=1.7564;4=637378052;20=1677783828741.16;7=21:52:37 
``

According to what above reported it appears that the transfer of data is done through websocket

Is it possible to get this data using websockify in order to have a live stream on a file

**Comment by DirectXMan12** [comment]
You can use the `--record` option to record a websockify session.  The output format is designed for consumption with noVNC's `vnc_playback.html` file, so you should be able to use that to play back the recording (if it's VNC traffic) and as information about the format.

**Comment by DirectXMan12** [comment]
Please let me know if you need any more information.

**Comment by famedoro** [comment]
@DirectXMan12 
Thanks for your response, I need to write on log file of all the traffic that comes from  serverpush.dot.it on port 7072.

I've tried this command: 

./run --record=logTest serverpush.dot.it:7072 
and 
and I have this message:
WARNING: no 'numpy' module, HyBi protocol will be slower
Usage:
    run [options] [source_addr:]source_port [target_addr:target_port]
    run [options] [source_addr:]source_port -- WRAP_COMMAND_LINE

run: error: Too few arguments


If I configure browser to use proxy on port 8888 and run this:
[root@galahad websockify-master]# ./run --record=logTest localhost:8888 serverpush.dot.it:7072
I have:
WARNING: no 'numpy' module, HyBi protocol will be slower
WebSocket server settings:
  - Listen on localhost:8888
  - Flash security policy server
  - No SSL/TLS support (no cert file)
  - Recording to '/root/Documenti/HackSellaHtml/websockify-master/logTest.*'
  - proxying from localhost:8888 to tradingpush.sella.it:7072
localhost.localdomain - - [02/Feb/2016 20:21:11] code 501, message Unsupported method ('CONNECT')
localhost.localdomain - - [02/Feb/2016 20:21:12] code 501, message Unsupported method ('CONNECT')
localhost.localdomain - - [02/Feb/2016 20:21:12] code 501, message Unsupported method ('CONNECT')
localhost.localdomain - - [02/Feb/2016 20:21:12] code 501, message Unsupported method ('CONNECT')

and the browser doesn't connect to https:\\myprovider.com

What I'm doing wrong ?
Thanks for your time.

**Comment by johnwmail** [comment]
> Please let me know if you need any more information.

Hi, after recorded the file record.7, how to vnc_playback.html to replay it?
Thanks.

**Comment by samhed** [comment]
Query parameters, like this:

your.webserver/vnc_playback.html?data=/path/to/record.7

**Comment by johnwmail** [comment]
> Query parameters, like this:
> 
> your.webserver/vnc_playback.html?data=/path/to/record.7

Thanks.

**Comment by sonisrje** [comment]
@johnwmail as you suggested in the above comments, I also tried the query parameters in my URL but it never yield the outcome. Here is my URL looks like: https://macc02vk4lrg8wn:6090/tests/vnc_playback.html?data=/Users/philips/Projects/ROCC/VNC-Explorations/noVNCViewer/websockify/record.266 

Also I always see the following error from the web page : Error loading recording: [object Event]

Can you please help me correcting my URL?

**Comment by samhed** [comment]
my bad, it seems noVNC's vnc_playback.html expects the recordings to be in a recordings-directory.

If vnc_playback.html is found at `noVNC/tests/vnc_playback.html`, the recordings should be in `noVNC/recordings/record.266`. 

So after moving your recording to that dir, your URL should be: https://macc02vk4lrg8wn:6090/tests/vnc_playback.html?data=record.266

**Comment by sonisrje** [comment]
@samhed Thanks for your reply. I created the recordings directory and move one of the recordings to it. Thereafter I am trying to access the URL as follows: https://macc02vk4lrg8wn:6090/tests/vnc_playback.html?data=record.2

But still it gives the below error:

**Loading record.2...
Error loading recording: ReferenceError: vncFrameData is not defined**

Can you please help me with this? I am also attaching the screenshot herewith.
<img width="737" alt="Screenshot 2020-08-27 at 3 17 21 PM" src="https://user-images.githubusercontent.com/44198033/91425209-767f5f80-e878-11ea-9d0f-42f1da0cc36a.png">

**Comment by CendioOssman** [comment]
It seems @samhed got a bit overzealous and broke this in 95632e41. :)

**Comment by CendioOssman** [comment]
The recordings are fine though, so I'm closing this issue. @samhed, please see if you can fix the issue in noVNC though.

**Comment by samhed** [comment]
Whoops, noVNC is now fixed in ecdd075672073410f65a7c8ceec9fd9951c9ffde and 7ce1b071ecb542efe26c5042e61d52dc5af138f5
