### ISSUE TITLE
when i run the run.exe,a error occured, please help me

### ISSUE THREAD

**Issue by zhangjianpinghik** [novnc/websockify#233]
D:\share\novnc for windows\kanaka-noVNC\utils>.\websockify\run.exe --web=
..  8902 10.6.21.69:5900
WARNING: no 'resource' module, daemonizing is disabled
WebSocket server settings:
- Listen on :8902
- Flash security policy server
- Web server. Web root: D:\share\novnc for windows\kanaka-noVNC
- No SSL/TLS support (no cert file)
- proxying from :8902 to 10.6.21.69:5900
  Traceback (most recent call last):
  File "run", line 5, in <module>
  File "websockify\websocketproxy.pyc", line 525, in websockify_init
  File "websockify\websocket.pyc", line 986, in start_server
  AttributeError: 'module' object has no attribute 'SIGCHLD'

**Comment by geostant** [comment]
Did you managed to fix that ?

**Comment by CendioOssman** [comment]
Already reported as #108.
