### ISSUE TITLE
git fsck complains: "contains zero-padded file modes"

### ISSUE THREAD

**Issue by jonasfj** [novnc/websockify#237]
When cloning I get:

```
Cloning into 'websockify'...
remote: Counting objects: 3599, done.
error: object 7a80ca084167b04a732640a2f18ec86af55377fb:contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
```

In my git config I have:

```
[transfer] 
        fsckobjects = true 
[fetch] 
        fsckobjects = true 
[receive] 
        fsckObjects = true 
```

I'm not sure how you would fix it... reimport will change all shas, so that isn't ideal...

**Comment by CendioOssman** [comment]
This is some git issue so I'm afraid it's not really something we have expertise to help you with. I suggest talking to Github or git.
