### ISSUE TITLE
Subprotocol negotiation fails if subprotocol list starts with a protocol unknown to websockify

### ISSUE THREAD

**Issue by cyberixae** [novnc/websockify#238]
I am using Websockify version 0.6.1+dfsg1-1 on Ubuntu. When I connect to Websockify with protocol listing ['binary', 'foo'] from Google Chrome the connection is established correctly. However ['foo', 'binary'] causes Websockify to terminate the connection. If I understand the specification correctly Websockify should just ignore 'foo' and go with the first subprotocol that works.

**Comment by CendioOssman** [comment]
The non-standard `binary`/`base64` is gone now. Can you test with the current `master`?

**Comment by DirectXMan12** [comment]
closing due to age.
