### ISSUE TITLE
websockify through apache reverse proxy

### ISSUE THREAD

**Issue by lucacapacci** [novnc/websockify#246]
Hi,
I need to set up a reverse proxy with apache and novnc and I followed the instructions posted here: https://github.com/kanaka/websockify/issues/149.

Do any of you have any problem after the connection is established?
I did set the reverse proxy as instructed by @sjpotter in his last comment and the browser correctly connected to the novnc server. The problem is that if for some time (just a few minutes) the user doesn't interact with the server, the connection silently drops.
And even stranger: nor the browser nor the novnc server detect the broken connection (or at least they don't report anything).

If I connect directly to the novnc server everything is good, so I guess I'm missing some configuration parameter inside apache.

thanks

**Comment by tkhm** [comment]
Same here. Any update?

**Comment by DirectXMan12** [comment]
We can't really help without any further information.  Additionally, this doesn't really seem to be a websockify problem.  I'm going to close this until we get more information.
