### ISSUE TITLE
405 = Specified method is invalid for this resource

### ISSUE THREAD

**Issue by csells** [novnc/websockify#248]
I've got websockify running against fibs.com:4321. When I connect to it on the command line via curl, I get the following:

root@a2e5c7cec307:/# curl localhost:8080
localhost - - [24/Sep/2016 16:09:11] code 405, message Method Not Allowed
<head>
<title>Error response</title>
</head>
<body>

<h1>Error response</h1>

<p>Error code 405.
<p>Message: Method Not Allowed.
<p>Error code explanation: 405 = Specified method is invalid for this resource..
</body>
root@a2e5c7cec307:/# curl localhost
curl: (7) Failed to connect to localhost port 80: Connection refused
root@a2e5c7cec307:/# curl localhost:8080
localhost - - [24/Sep/2016 16:09:38] code 405, message Method Not Allowed
<head>
<title>Error response</title>
</head>
<body>

<h1>Error response</h1>

<p>Error code 405.
<p>Message: Method Not Allowed.
<p>Error code explanation: 405 = Specified method is invalid for this resource..
</body>

When I attempt to connect to it via a Websock object, I get:

WebSocket connection to 'ws://localhost:8080/' failed: Connection closed before receiving a handshake response

Here's my code:

```
telnet = new Websock();
telnet.open("ws://localhost:8080");
```

What am I doing wrong?

**Comment by AaronZhangL** [comment]
I got same error code.
My starting command is:
`$ ./utils/websockify/websockify/websocketproxy.py --target-config=/home/test-user/fc_vnc_tokens 9001 --cert ./utils/self.pem`

**Comment by CendioOssman** [comment]
What does the log from websockify say?

**Comment by AaronZhangL** [comment]
The log is below:
```
[test-user@test noVNC]$ ./utils/websockify/websockify/websocketproxy.py --target-config=/home/test-user/fc_vnc_tokens/az.
conf 29876 --cert ./utils/self.pem
WebSocket server settings:
  - Listen on :29876
  - SSL/TLS support
  - proxying from :29876 to targets generated by TokenFile
xxxx.xxxx.local - - [20/Sep/2017 17:50:39] code 405, message Method Not Allowed
xxxx.xxxx.local - - [20/Sep/2017 17:50:53] code 405, message Method Not Allowed
```

**Comment by CendioOssman** [comment]
How are you accessing this? You haven't specified `--web` so it will only allow websocket connections.

**Comment by flexsingit** [comment]
I am also having the same issue here is the command that i am running


./run --token-plugin TokenFile --token-source /home/himanshu/noVNC/target.config.d/kiosk_first 6080

**Comment by CendioOssman** [comment]
As with the previous guys, you have to specify `--web` if you also want it to serve normal files (e.g. the noVNC files). Without that it is only a websocket proxy and you'll need a separate web server to serve files.
