### ISSUE TITLE
Advice: Add recording feature to websockify.js

### ISSUE THREAD

**Issue by darkpixel** [novnc/websockify#249]
I'm hoping someone can give me a little bit of advice with websockify.js.

I played around for a few weeks writing my own implementation before I noticed you had websockify for node, and I figured I would try and update websockify.js rather than open sourcing mine.

In my app, I am able to take a websocket connection in, and forward it through a TCP socket to connect to a VNC session using novncd.  But when I grab incoming data from the websocket or the TCP socket, and write it to a file (like the record function in the python version) I don't get anything like the data I see in the python version.  I attempted to duplicate the decode_hybi and encode_hybi functions and pulling frames out of the socket--but I end up with garbage.  I think that's because the 'ws' library is already handling the encoding/decoding.

Can someone give me a kick in the right direction on massaging the data in Node and/or what the format is that the python version spits out?

i.e. the Python spits out a file like this.

```
var VNC_frame_encoding = 'binary';
var VNC_frame_data = [
'{834{RFB 003.008\n',
'}876}RFB 003.008\n',
'{907{\x02\x02\x10',
'}941}\x10',
'{969{\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02STDVVNCAUTH_',
'}1002}\x00\x00\x00\x02',
```

I know it's basically dumping a long JavaScript string into a variable, but I'm not familiar with the format.

Thanks in advance.

-A

**Comment by DirectXMan12** [comment]
Ok, so the python format is a bit strange, but basically, the format is basically as thus:

- the direction of the curly braces denote the direction of the data -- `}` denotes data coming from the websocket client, while `{` denotes data coming from the proxied server

- the number between the curly braces is a timestamp (time since start)

- the data after the curly braces is the contents of the WebSocket frame body, unmasked

This is written as an array called `VNC_frame_data`, where each element of the array is one of these strings representing a websocket frame.

For example, the snippet above says

> at time 874, the proxied server sent the data `RFB 003.008\n`

> at time 876, the client replied with the data `RFB 003.008\n`

and so on.  There should also be a variable called `VNC_frame_encoding` that's set to the string `'binary'` (indicating that this is not the non-longer-supported "base64" encoding).

**Comment by DirectXMan12** [comment]
The recording format is a bit strange, but it basically works like this:

- The variable `VNC_frame_encoding` denotes the encoding that body of the frame descriptions (see below) is in.  It should be set to `"binary"` (previously `"base64"` was used, but that's no longer supported).

- The variable `VNC_frame_data` contains descriptions of the WebSocket frames sent and received by Websockify, as elements of an array.  Each element of the array describes one frame, and has the following format:

    - the direction of the curly braces indicates the direction in which the data flowed: `{` indicates data flowing from the proxied server to the client, while `}` indicates data coming from the client, going to the proxied server

    - the number between the curly braces is a timestamp.  It indicates time since the connection started.

    - the data after the second curly braces is the body of the WebSocket frame (no header), unmasked (when masking is applicable).  Non-printable characters should be escaped as appropriate for a JS string.

For example, the first few elements of the snippet above say the following:

> at time 834, the server sent the data `RFB 003.008\n`

> at time 876, the client replied with `RFB 003.008\n`

and so on.

Hope that helps 😄 !  Feel free to ask further questions in this issue, but I'm going to close it for now.

**Comment by darkpixel** [comment]
I appreciate the info.  I had the first part figured out by reading the Python.  Where I'm confused is after that part.

```
'{969{\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02STDVVNCAUTH_',
```

Initially it looks like the data is possibly ASCII to hex, but at the end of the string it's obviously not.

In the python version (https://github.com/kanaka/websockify/blob/master/websockify/websocket.py#L319 and https://github.com/kanaka/websockify/blob/master/websockify/websocket.py#L398) it looks like the data being written to the recording file is already hybi encoded or decoded.

If that's the case, I think I'll have to dig through the 'ws' library and use their encode/decode utilities whenever I receive a complete message and then encode it for writing to the record stream.  Does that sound correct, or am I way off? ;)

**Comment by DirectXMan12** [comment]
> Initially it looks like the data is possibly ASCII to hex, but at the end of the string it's obviously not.

It's effectively the array of bytes encoded as a javascript string.  The function that the Python version uses to do that encodes the printable ascii characters in printable form, and the rest are encoded in escaped hex form (which is the way to represent arbitrary bytes in JS strings), but as long as it resolves to the right string of bytes in JS, you're fine (so you can escape every character if you want).

> In the python version (https://github.com/kanaka/websockify/blob/master/websockify/websocket.py#L319 and https://github.com/kanaka/websockify/blob/master/websockify/websocket.py#L398) it looks like the data being written to the recording file is already hybi encoded or decoded.

The data being written is actually just the non-encoded payload of the frame, unmasked when necessary.  So whatever the pre-encode/post-decode payload is, you can use that.

**Comment by darkpixel** [comment]
Thanks again for the info.  I'll give it a shot and submit a PR if I can come up with something.

**Comment by darkpixel** [comment]
I was running an old version of websockify, and novnc, so I updated both.  I had several old base64 recordings that *were* working with the vnc_playback.html in the tests directory.  They didn't play, so I assumed it was because of the change to the new binary format.  I ran b64-to-binary.pl against them and they still aren't playing.  So I decided to test with the unknown-if-working version spit out by my changes to websockify.js, and that isn't working either.

I get the following from console:
```
vnc_playback.html?data=output:52 Loading output
2016-10-07 11:04:44.905 vnc_playback.html?data=output:52 VNC_frame_data.length: 501
2016-10-07 11:04:50.538 vnc_playback.html?data=output:52 Starting realtime playback [3 iteration(s)]
2016-10-07 11:04:50.558 playback.js:34 Uncaught TypeError: this._updateState is not a functionrfb.connect @ playback.js:34next_iteration @ playback.js:58start @ vnc_playback.html?data=output:106onclick @ vnc_playback.html?data=output:13
```

Is vnc_playback.html working at the moment in HEAD?

**Comment by darkpixel** [comment]
* issues and PRs in the noVNC repo.

**Comment by samhed** [comment]
> TypeError: this._updateState is not a function

Quite substantial changes were made to rfb.js recently: https://github.com/kanaka/noVNC/pull/651

I have to admit that I haven't tested vnc_playback.html since then. I am quite swamped at the moment, any assistance in troubleshooting with regards to this would be greatly appreciated!

**Comment by darkpixel** [comment]
I dug around, but I'm totally lost in the code.  playback.js bombs here: https://github.com/kanaka/noVNC/blob/master/tests/playback.js#L33 because 'this' (the RFB object) doesn't have an _updateState() function.  It looks like updateState was moved to the UI module, but there's also a few references to _rfb_connection_state().  Neither one is available on the RFB object in playback.js.  Any pointers in the right direction?

**Comment by samhed** [comment]
Absolutely! I'll try to help. Update state was renamed to updateConnectionState because it doesn't handle the init states anymore. The function you see in ui.js is the function triggered by the connection state change callback.

ProtocolVersion however, is a init state, a part of the connection state "connecting". On that line in playback.js, I believe it should work if you instead run this._updateConnectionState('connecting')

**Comment by samhed** [comment]
Nvm, just set _rfb_init_state directly to ProtocolVersion

**Comment by samhed** [comment]
f9e26cdb323cecb9eb814b0232d4a25878be8f19 fixes that issue

**Comment by darkpixel** [comment]
Thanks @samhed.  I looked at the changes, but they definitely go over my head at the moment.  Still too green with the code.  The commits appear to fix the playback issue I was having.

I still have some digging to do with the output of the nodejs version, as I'm not matching the data format.

```
Error while connecting: Invalid server version 4220303
```

Thanks for the help, I appreciate it.

**Comment by darkpixel** [comment]
I think I'm close.  I modified websockify.js to record the websocket session here: https://github.com/novnc/websockify/compare/master...darkpixel:feature/249-recording-in-node-js

Using the version of vnc_playback in latest release of noVNC, I get no errors in the console, but I don't see the recorded session.

![screenshot from 2017-05-16 20-46-51](https://cloud.githubusercontent.com/assets/158380/26137753/00d442ce-3a79-11e7-8325-17410bcf130e.png)

![screenshot from 2017-05-16 20-46-59](https://cloud.githubusercontent.com/assets/158380/26137760/054771aa-3a79-11e7-9222-f4e93c3a802e.png)

**Comment by darkpixel** [comment]
I would appreciate any advice.

**Comment by CendioOssman** [comment]
Could you attach an example recording?

**Comment by darkpixel** [comment]
I rename this file to 'test_recording' and stick it in the 'include' direcetory and hit ``vnc_playback.html?data=test_recording```

[test_recording.txt](https://github.com/novnc/websockify/files/1009082/test_recording.txt)

**Comment by darkpixel** [comment]
If I had to guess, there's something I'm missing about 'printable characters' that @DirectXMan12 said, and/or there's some magic about frames that I'm not getting.

**Comment by CendioOssman** [comment]
I see the problem. All your lines have an extra "\n" at the end. That is not part of the data so you're screwing up the protocol stream by adding that.

**Comment by darkpixel** [comment]
[test_recording.txt](https://github.com/novnc/websockify/files/1011569/test_recording.txt)

Thanks.  I fixed that locally, created a new test recording, and it plays the same as before, but I don't actually see anything on the canvas.

I suppose I need to grab a recording using the python version and see if that displays.

**Comment by darkpixel** [comment]
Sorry, the playback isn't the same as before.  It's now telling me how many iterations it ran and how long it took.
![screenshot from 2017-05-18 09-27-29](https://cloud.githubusercontent.com/assets/158380/26213034/5ad1df5a-3bac-11e7-8398-12c43d5edd7c.png)

**Comment by CendioOssman** [comment]
The next thing I noticed is that your recording shows noVNC picking auth scheme 2, not 16. Unfortunately it's not possible to play back a recording that doesn't match noVNC's current behaviour.

**Comment by darkpixel** [comment]
I'm recording the traffic between noVNC and TightVNC.  I can connect just fine.  Why would the recording of a good connection produce a different auth scheme?

**Comment by CendioOssman** [comment]
I don't know. Neither 0.6.2 nor master will select VNC auth if Tight auth is available. Do you have local modifications to your noVNC?

**Comment by darkpixel** [comment]
Just compared my source to double-check.  I forgot I applied  https://github.com/novnc/noVNC/issues/364#issuecomment-44927357 after TightVNC broke in more recent versions of noVNC.  I'll try my initial test with something other than TightVNC and verify it works, then see what I can do about fixing the TightVNC playback.

**Comment by CendioOssman** [comment]
Great. Hopefully it should be fine after that.

**Comment by darkpixel** [comment]
I'm still missing something.

Using the the python version of websockify: ```./run --cert self.pem --ssl-only --record=test.rec 127.0.0.1:9988 192.168.42.41:5900```

This connects from the patched version of noVNC I mentioned above to a Windows box running TightVNC and produces a test.rec file.  Using the noVNC playback_vnc.html file I am able to play back the recorded session.

Using the *node* version that I tweaked to record: ```./websockify.js --cert self.pem --dir tmp/ 127.0.0.1:9988 192.168.42.41:5900```

This connects from the patched version of noVNC I mentioned above to a Windows box running TightVNC and produces a recording.  Using the exact same noVNC playback_vnc.html file as in the previous test, I get the message ```util.js:220  Msg: Server wanted tunnels, but doesn't support the notunnel type```

It would seem to me that there's a problem with my recording file rather than noVNC, or maybe I'm misunderstanding something about the way it plays back the negotiation.

Regardless, I will get a second test box spun up this weekend with a non-TightVNC server on it and test it that way.

**Comment by kanaka** [comment]
It would be interesting to see the first 15 or so lines of each recording to be able to compare byte for byte what the difference is in the recording entries.

**Comment by darkpixel** [comment]
Damn.  Too many working directories.  Found the problem and fixed it.

Give me a bit of time to clean up and do a proper PR so everyone can critique.

**Comment by darkpixel** [comment]
Created PR #284
