### ISSUE TITLE
running websockify as daemon

### ISSUE THREAD

**Issue by ecownomist** [novnc/websockify#258]
I'm having issues running websockify as a daemon using ./run -D IP:Port

I want to run it in the background so that I can connect via web browser and view it without having to open, run the launch.sh code from noVNC and connecting by leaving terminal open.

looking for a solution to run websockify in the background without terminal open. not sure if -D will do the trick

running on debian 7

**Comment by ValHook** [comment]
You should make it a systemctl daemon

**Comment by DirectXMan12** [comment]
closing due to age
