### ISSUE TITLE
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

### ISSUE THREAD

**Issue by jankeromnes** [novnc/websockify#266]
The WebSockify bridge of noVNC seems to be broken since commit 4099949984eb80ef33c2d0dd216991124975a5d2.

The error that appears in Chrome's console is:

```js
websock.js:278 WebSocket connection to 'wss://janitor.technology/websockify' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
```

I had a look at the headers received from WebSockify's server, and indeed it seems that `Sec-WebSocket-Protocol` is no longer being sent.

Before 4099949984eb80ef33c2d0dd216991124975a5d2:

```
HTTP/1.1 101 Switching Protocols
Server: WebSockify Python/2.7.12
Date: Tue, 07 Feb 2017 15:52:33 GMT
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: yHBB/hXTWGaTjk29VQhWk2not24=
Sec-WebSocket-Protocol: binary
```

After 4099949984eb80ef33c2d0dd216991124975a5d2:

```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: ZefPJQjbgtmJGvzKFp7JvLWpDvI=
```

Maybe it could help to continue sending `Sec-WebSocket-Protocol: binary` in the WebSocket headers? Or am I doing something wrong here?

**Comment by CendioOssman** [comment]
Ah, right. Apparently you have to pick one of the options. The non-standard 'binary' and 'base64' have been removed from the code here, but I guess there might be other code that still follows the old principle. I'll see if I can get some compatibility code in there.

**Comment by CendioOssman** [comment]
df317822d6af7dc954913e5a9947d36b33bfbf33 should fix this.

**Comment by jankeromnes** [comment]
I confirm that the issue is fixed on my side, thanks a lot for resolving these so quickly!
