### ISSUE TITLE
Websockify behind one iptables bridge problem

### ISSUE THREAD

**Issue by bigrck64** [novnc/websockify#269]
Hello !

I've a working novnc + websockify service on a debian server.
When I'm connecting directly on the IP of the server over http://debian1:6080/ it's working perfectly.

However, when I'm using a debian bridge on my gateway ethernet link, it's no more working.
The debian iptables bridging is something I'm using since 20 years without any problem on TCP or UDP flow, it's the first time one TCP protocol is failing :)

Did someone have any idea why it's not working ? here are my firewall settings on the debian bridge who is filtering the internet paquets :

# Create special chain KEEP_STATE
iptables -N KEEP_STATE
iptables -F KEEP_STATE

# Drop bad states
iptables -A KEEP_STATE -m state --state INVALID -j DROP
iptables -A KEEP_STATE -m state --state RELATED,ESTABLISHED -j ACCEPT

# Deny bad packets
iptables -A FORWARD -p tcp --tcp-flags ALL FIN,URG,PSH -m limit --limit 5/minute -j LOG --log-level notice --log-prefix "NMAP-XMAS: "
iptables -A FORWARD -p tcp --tcp-flags ALL FIN,URG,PSH -j DROP
iptables -A FORWARD -p tcp --tcp-flags SYN,FIN SYN,FIN -m limit --limit 5/minute -j LOG --log-level notice --log-prefix "SYN/FIN: "
iptables -A FORWARD -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN,RST -m limit --limit 5/minute -j LOG --log-level notice --log-prefix "SYN/RST: "
iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN,RST -j DROP

# Drop RST/ACKs to limit OS detection through pinging
iptables -A FORWARD -p tcp --tcp-flags RST RST,ACK -m limit --limit 5/minute -j LOG --log-level notice --log-prefix "RST/ACK: "
iptables -A FORWARD -p tcp --tcp-flags RST RST,ACK -j DROP

# Pass all boxes to the keep_state chain
iptables -A FORWARD -j KEEP_STATE

# Allow all outgoing traffic
iptables -A FORWARD -s 1.2.3.0/25 -j ACCEPT

# NoVNC WebSocket
iptables -A FORWARD -p tcp -d 1.2.3.9 --dport 6080 -j ACCEPT

# Set to drop all packets not accepted by rules above
iptables -A FORWARD -j DROP

**Comment by CendioOssman** [comment]
Nothing obviously wrong, so I think you'll have to enable some logging in those rules to figure out where the packets end up. A bit of tcpdump/wireshark probably doesn't hurt either.

**Comment by bigrck64** [comment]
Good idea about wireshark, I'll try to figure why thoses rules are not working for NoVNC.
