### ISSUE TITLE
Getting "error: can't copy 'include\base64.js': doesn't exist or not a regular file" When following "Compiling Websockify as Windows Executable" 

### ISSUE THREAD

**Issue by DayVidZhou** [novnc/websockify#270]
in step 4 when I cd to the directory where websockify folder is and run 
"[full path of Portable Python install]\App\python.exe setup.py py2exe --includes numpy"
I get the following error
error: can't copy 'include\base64.js': doesn't exist or not a regular file

![image](https://cloud.githubusercontent.com/assets/9309271/23728113/12e675ee-0429-11e7-9b93-c0ecffbfd34d.png)

**Comment by CendioOssman** [comment]
Sorry about that. It was overlooked when I removed base64.js. It should be fixed in 61b1b8aef75a6751bc86e06858db011a813081ae.
