### ISSUE TITLE
Getting "error: can't copy 'include\web-socket-js\WebSocketMain.swf': doesn't exist or not a regular file" When following "Compiling Websockify as Windows Executable"

### ISSUE THREAD

**Issue by DayVidZhou** [novnc/websockify#271]
in step 4 when I cd to the directory where websockify folder is and run
"[full path of Portable Python install]\App\python.exe setup.py py2exe --includes numpy"
I get the following error
error: can't copy  'include\web-socket-js\WebSocketMain.swf': doesn't exist or not a regular file

![image](https://cloud.githubusercontent.com/assets/9309271/23758877/1a667996-04b9-11e7-9715-a950a646f18e.png)

**Comment by CendioOssman** [comment]
Fixed in 5b7f722. That should hopefully be the last bit as I can install just fine here now. Sorry about that.
