### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by joeytall** [novnc/websockify#272]
Hi, novnc would not work if the server doesn't enable http.
For example, If I connect to my server as http://myservervnc, it works
but https://myservervnc won't work

Is it supported?
If yes, please help.

**Comment by samhed** [comment]
It works perfectly fine:

https://github.com/novnc/websockify/wiki/Encrypted-Connections

**Comment by joeytall** [comment]
Hi, thanks for the reply.
Can you give me more detail on how to make HTTPS work.
I have no idea what to configure or change to enable HTTPS support.

I found self.pem code in utils/launch.sh, 
but I didn't even include that file and novnc works perfectly fine in HTTP.

Are there any examples I can use? thanks.
