### ISSUE TITLE
SSL error: no shared cipher

### ISSUE THREAD

**Issue by kkthx** [novnc/websockify#276]
Hi
I'm trying to set up noVNC and websockify with ssl certificate.
I obtained cert using zerossl.com, have 2 files:
1. private key
2. concatenated file: my domain certificate and intermediate ca certificate

I'm trying to run it (on windows) like this:
websockify\websockify.exe 443 localhost:5900 --web=./ --cert=zzz_zerossl.pem --key=zzz_private.key --ssl-only --verbose

and getting error:
on console:

>   1: handler exception: [Errno 1] _ssl.c:503: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
>   1: Traceback (most recent call last):
>   File "websocket.pyc", line 723, in top_new_client
>   File "websocket.pyc", line 575, in do_handshake
>   File "ssl.pyc", line 372, in wrap_socket
>   File "ssl.pyc", line 134, in __init__
>   File "ssl.pyc", line 296, in do_handshake
> SSLError: [Errno 1] _ssl.c:503: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
> 

on firefox:

> SSL_ERROR_NO_CYPHER_OVERLAP

How to fix it?

Regards,

**Comment by samhed** [comment]
First of all, can you get it working without ssl on windows?

**Comment by braney** [comment]
I encountered a similar issue (in Linux), but found a solution.  I had the SSL connection working fine with a self-signed certificate, but wanted it to work without having to setup a security exception in the browser.

I obtained a server certificate signed by InCommon.org.  Like you, I tried passing the concatenated file (containing the server certificate + the intermediate CA certificates) via `--cert='file.pem'`, and got the "no shared cipher" error.  My command-line was very similar to yours:

`utils/websockify/run 5800 localhost:5900 --web . --cert ../myhost_and_ca.cer --key ../myhost.key --ssl-only --verbose`

I found that it works if the file I specify to `--cert` contains *only* the server certificate, without concatenating the intermediate CA certificates.  My browser already knew of the InCommon CA, so I really didn't need the intermediate CA certificates anyway.  Still, it suggests that passing the concatenated file to websockify is the problem.

If intermediate CA certificates are required to secure your connection, this might be of help:
I found that the call to `ssl.wrap_socket()` in websockifyserver.py could be passed a file containing intermediate CA-certificates file via the `ca_cert` option.

**Comment by DirectXMan12** [comment]
> If intermediate CA certificates are required to secure your connection, this might be of help:
I found that the call to ssl.wrap_socket() in websockifyserver.py could be passed a file containing intermediate CA-certificates file via the ca_certs option.

we should open a separate bug to track that this
