### ISSUE TITLE
websockify and MySQL

### ISSUE THREAD

**Issue by mdiener** [novnc/websockify#279]
Hi there!

I'm trying to connect to a MySQL database with websockify and have it available in a browser (in the end). Right now, however, I am stuck at creating a lasting connection. I can open a connection and the websocket reacts to incoming requests, but every time I try to connect, the connection is immediately terminated with the response `handler exception: [Errno 111] Connection refused`.

This is my setup:
I open websockify and connect to mysql with the following command:
`websockify 127.0.0.1:8080 -- /usr/bin/mysql -uanalytics -p#####` which opens a connection to MySQL and provides me with the dialog to enter commands.
On the client side I am using node with wscat to test the setup:
`wscat -c ws://127.0.0.1:8080 -s binary`
which returns the following two lines immedately:
`connected (press CTRL+C to quit)`
`disconnected`

I'm honestly not sure if it is a problem with MySQL or websockify, but connecting to MySQL without the websockify layer works without a problem.

p.s.: I've seen the ticket https://github.com/novnc/websockify/issues/51, which is where I got the command for websockify from.

Any help would be greatly appreciated!

Best,
Michael

**Comment by CendioOssman** [comment]
You need to start MySQL in daemon mode, not as an interactive program. The wrapping function just modifies which port is used, it doesn't provide network for console applications.

However since the `mysql` command works it seems like you already have the server up and running. So just start websockify in it's normal proxy mode and give it the host and port of your mysql server.

**Comment by kanaka** [comment]
@mdiener The websockify command wrap mode is used to start a server and expose that service's listen port as a WebSocket port. In other words, if you were going to use wrap mode with mysql it would be to wrap the mysqld service, not the mysql client (the client would be something you write in JS that commincates over websockets to the server). Also, it is assumed that the websockify listen port matches the initial port of the service that is being wrapped. So using command mode would look more like this:

```
./websockify 127.0.0.1:8080 -- mysqld --port 8080 ...
```

However, the wrap command mode of websockify is mostly a development tool. As @CendioOssman mentioned, it's probably better to run mysqld separately and then have a separate websockify process to bridge to the mysqld port:

```
./websockify 127.0.0.1:8080 127.0.0.1:3306   # 3306 is the running mysqld listening port
```

Then you would connect using a WebSocket client (i.e. a browser) to 127.0.0.1:8080. This would triggers a normal TCP connection to 127.0.0.1:3306. The client would need to be some sort of mysql client (running in JavaScript) for anything interesting to work of course.

**Comment by mdiener** [comment]
Ohhhh I get it! Okay, yeah, for some reason I did not make that connection to run the server with websockify instead of the client.

Thank you for the heads up with the development/production environment. I'm just using this for testing things, so I assume it should be fine to wrap the server command directly. Of course in a production environment there should be some more security/layers.

Thanks again for clearing things up! I will try that later this week.

**Comment by kanaka** [comment]
@mdiener the command wrapping isn't particularly sophisticated so it may or may not work with mysqld. So you might have to run them separately regardless. I've only tried it with simple servers myself (telnetd, etc). But if it does work for you, please report back here with any details for posterity. Thanks!

**Comment by mdiener** [comment]
I actually do run them separately now. It works, though of course I now face the trouble of talking directly (without a client) to MySQL. But that's a completely different topic :)

Thanks again for the very quick help! That is much appreciated!
