### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by Craigzyc** [novnc/websockify#283]
Sorry to make this an issue as its more of just a question. 
I can not see anything clearly stating if this will work. 
If I have tigerVNC on a windows machine can I use websockify on a neighboring linux box to proxy the connection or do I have to use websockify on the machine running the service?

**Comment by kanaka** [comment]
Either will work as long as the system running the websockify instance can make network connections to the tigerVNC on the other system i.e. tigerVNC is listening on an public port (i.e. not just localhost) and there is no firewall blocking access on either side or in between.

**Comment by Craigzyc** [comment]
Thank you!
