### ISSUE TITLE
cannot serialize '_io.textiowrapper' object

### ISSUE THREAD

**Issue by stevenmi** [novnc/websockify#288]
i use websokify in windows, compile with python 3.4 and py2exe
and i deal with  SIGCHLD on Windows  according to
https://github.com/novnc/websockify/commit/3ee9ff7f4d5b27c77c75e246d4ac8d642049b02f#comments.

i can compile a run.exe and it work well .but when i connect it with novnc.
the error occur:cannot serialize '_io.textiowrapper' object. run.exe:error: no such option:--multiprocessing-fork

how can i solve this problem

**Comment by CendioOssman** [comment]
> i can compile a run.exe and it work well .but when i connect it with novnc.
> the error occur:cannot serialize '_io.textiowrapper' object.

Odd. Do you get this error if you use Python directly and not py2exe?

> run.exe:error: no such option:--multiprocessing-fork

Windows doesn't have `fork()`, so that particular mode will not work.

**Comment by stevenmi** [comment]
@CendioOssman how can i use multiprocess in windows.

**Comment by CendioOssman** [comment]
I don't know to be honest. Windows support isn't properly fixed in websockify.py.

**Comment by stevenmi** [comment]
@CendioOssman  thanks

**Comment by CendioOssman** [comment]
multiprocessing needs lots of work to function on Windows, so I'm closing this specific issue.
