### ISSUE TITLE
undefined reference to `bzero'  crosse compile

### ISSUE THREAD

**Issue by mohammadalnatour** [novnc/websockify#289]
pp-wrapper-gcc  websockify.o websocket.o base64.o -lssl -lcrypto -lresolv -o websockify
websockify.o: In function `proxy_handler':
websockify.c:(.text+0x1200): undefined reference to `bzero'
websocket.o: In function `parse_handshake':
websocket.c:(.text+0x16d0): undefined reference to `bcmp'
websocket.o: In function `do_handshake':
websocket.c:(.text+0x23a8): undefined reference to `bcmp'
websocket.o: In function `start_server':
websocket.c:(.text+0x37bc): undefined reference to `bzero'
collect2: ld returned 1 exit status
make: *** [websockify] Error 1

**Comment by CendioOssman** [comment]
What platform are you compiling for?

**Comment by CendioOssman** [comment]
No response.
