### ISSUE TITLE
websokify.js support multi targets like python version --target-config

### ISSUE THREAD

**Issue by stevenmi** [novnc/websockify#290]
how can i use websokify.js like python version --target-config to config multi targets. or there is no way to 
Achieve this goal

**Comment by stevenmi** [comment]
i write a websokify js multi version. is there any one optimize it
[websockify-multi.zip](https://github.com/novnc/websockify/files/1117599/websockify-multi.zip)

**Comment by CendioOssman** [comment]
I'm afraid websockify.js does not have that functionality yet. If you wish to add it, then please open a pull request so that we can review the code.
