### ISSUE TITLE
binary support in C version Websockify

### ISSUE THREAD

**Issue by imvic999** [novnc/websockify#294]
Seems C version did not support array buffer yet, right?

**Comment by CendioOssman** [comment]
I assume you mean binary mode, and it does indeed lack support for that.

**Comment by paolovolpi** [comment]
I wrote a patch to enable HyBi IETF 6455 binary support to the C version of websockify. Please note that It is affected by novnc/noVNC#890 as the python one.
[HyBipatch.txt](https://github.com/novnc/websockify/files/1276858/HyBipatch.txt)

**Comment by CendioOssman** [comment]
Could you send us the patch as a pull request?

**Comment by paolovolpi** [comment]
I've found a pull request #210 for the same feature by @samuelbrian. I'm going to test it and I will report to you if it is ok.
