### ISSUE TITLE
Connect multiple vnc users sessions using noVNC client on a single host

### ISSUE THREAD

**Issue by thrinethratechhara** [novnc/websockify#297]
Hello,

I am running a VNC client in a dedicated ubuntu. I have installed tight VNC server in windows 10 machine. I wish to allow multiple VNC sessions for all VNC users in my windows machine through noVNC client. Here the host/ip address is same for all hosts. I have a unique port number, password for all users created from Windows 10 machine. How can I use this in noVNC client such that all users should access their own VNC sessions with intercepting other's VNC session.

Is it possible to attain this. I should configure my client like url given below.

https://kanaka.github.io/noVNC/noVNC/vnc.html

Could you please help to achieve this. I have gone through the configuration file and I din't get any idea about this. 

Best Regards,
RK

**Comment by CendioOssman** [comment]
You would need to run a separate websockify for each user, or you would use the token plugin:

https://github.com/novnc/websockify/wiki/Token-based-target-selection

However it would require the users to go in and modify the advanced settings in noVNC. If you want something more easy to use then I'm afraid you'll have to extend noVNC with that yourself.

**Comment by CodingYiyi** [comment]
@CendioOssman can this solution work well in windows?
