### ISSUE TITLE
websocket openning handshake was cancled

### ISSUE THREAD

**Issue by niyayun** [novnc/websockify#300]
when i use the https , the noVNC client will use the wss://host+port+path to connect to websockify proxy. and i am already start proxy with websockify and use the --cert .but chrome browser still 
has a error: websocket opening handshake was cancled.i want to know the reason?thank you very much.

**Comment by CendioOssman** [comment]
Could be a certificate problem. What does the server log say?
And what does chrome say if you go to `https://host:port`?

**Comment by CendioOssman** [comment]
No response.
