### ISSUE TITLE
problem connecting to websocket

### ISSUE THREAD

**Issue by yugushihuang** [novnc/websockify#301]
**I have installed novnc and tightvnc on my ubuntu 16.04 and try to connect. When I navigate to the URL, the webpage appears but when I click the "Connect" button, it just show "Failed to connect to the server". I am not very familiar with VNC and hope to get some help to set it up right**

The messages show below -->
  warnings.warn("no 'numpy' module, HyBi protocol will be slower")
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /home/yxiao/Desktop/noVNC/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5901

Navigate to this URL:

    http://ubuntu:6080/vnc.html?host=ubuntu&port=6080

Press Ctrl-C to exit

127.0.0.1: ignoring socket not ready
127.0.0.1 - - [28/Sep/2017 15:03:39] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
127.0.0.1 - - [28/Sep/2017 15:03:39] 127.0.0.1: Path: '/websockify'
127.0.0.1 - - [28/Sep/2017 15:03:39] connecting to: localhost:5901
127.0.0.1: ignoring socket not ready
127.0.0.1: ignoring socket not ready

Thank you very much for your help ahead!

**Comment by CendioOssman** [comment]
Can you check the browser console for errors?

Which browser are you using?

**Comment by halmos** [comment]
I'm having same issue running OS X 10.11. using system VNC. Firefox 55.0.3.
FireFox Web console reports the following with `./utils/launch.sh --vnc localhost:5900`
```
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]  vnc.html
unreachable code after return statement  babel-worker.js:13014:4
unreachable code after return statement  babel-worker.js:13026:4
unreachable code after return statement  babel-worker.js:43349:1
unreachable code after return statement  babel-worker.js:13014:4
unreachable code after return statement  babel-worker.js:13026:4
unreachable code after return statement  babel-worker.js:13014:4
unreachable code after return statement  babel-worker.js:13026:4
unreachable code after return statement babel-worker.js:43349:1
Password is required  ui.js!transpiled:1077:21
WebSocket on-close event
```
Terminal reports the following:
```
Warning: could not find self.pem
Using local websockify at /Users/erik/Documents/librarystack/VM/noVNC/websockify/run
Starting webserver and WebSockets proxy on port 6080
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /Users/erik/Documents/librarystack/VM/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5900


Navigate to this URL:

    http://eriks-MBP:6080/vnc.html?host=eriks-MBP&port=6080

Press Ctrl-C to exit


124.2.168.192.in-addr.arpa - - [06/Oct/2017 08:52:28] 192.168.2.124: Plain non-SSL (ws://) WebSocket connection
124.2.168.192.in-addr.arpa - - [06/Oct/2017 08:52:28] 192.168.2.124: Path: '/websockify'
124.2.168.192.in-addr.arpa - - [06/Oct/2017 08:52:28] connecting to: localhost:5900
192.168.2.124: ignoring socket not ready
192.168.2.124: ignoring socket not ready
192.168.2.124: ignoring socket not ready
handler exception: [Errno 57] Socket is not connected
```

I've tested  that OS X VNC is working and is running on port 5900.
Any thoughts on how to debug this?
thanks.

**Comment by CendioOssman** [comment]
Not the same issue. The `ignoring socket not ready` has nothing to do with either of your issues.

You seem to have a compatibility issue with macOS' server. Please file a bug with noVNC/noVNC instead.

**Comment by yorak** [comment]
I'm having the same issue also. Is there any way we could provide more information? 
Docker version 17.09.0-ce, build afdb6d4
Ubuntu 16.04.3 LTS @ Azure

**Comment by CendioOssman** [comment]
Same question as earlier, what does the browser console say? And which browser?

**Comment by yugushihuang** [comment]
The browser console says:
rfb.js:592 Failed when connecting: Failed to connect to server ( (code: 1006))

And the browser is Chrome.

**Comment by CendioOssman** [comment]
Is that the only message in the console?

Does it work with other browsers? E.g. Firefox? Does it show more info in the console?

**Comment by andrusstrockiy** [comment]
> Is that the only message in the console?
![image](https://user-images.githubusercontent.com/2841979/32077264-7a6b05a2-baab-11e7-900d-62e3256d7d62.png)
> Does it work with other browsers? E.g. Firefox? 
It works with Chromium 
<pre>
Version 62.0.3202.62 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
</pre>
 but failed with Firefox check my version is attached bellow
![image](https://user-images.githubusercontent.com/2841979/32077349-cad6b5d6-baab-11e7-87e9-76ea384690e4.png)
with disabled AdBlock.

**Comment by CendioOssman** [comment]
If it works in Chromium then you are not seeing the same issue as @yugushihuang. Please open a new issue. And please include the console output in Chromium for comparison in that new issue.

**Comment by andrusstrockiy** [comment]
@CendioOssman could we stay within same issue, i really don't want create a lot of issues,

> And please include the console output in Chromium for comparison in that new issue.
![image](https://user-images.githubusercontent.com/2841979/32102159-d1ed0be0-bb23-11e7-8397-4afdbcf0c99c.png)

Also is there is any particular requirements for browsers? 
Meanwhile I asked my team members on different platform i,e windows  and mac to test , so far it was negative feedback from them. We tried:

1. Chrome on windows 62.0.3202.75 ( Win 10)
2. Firefox on windows Firefox 56.0.2 (Win 10)
3. Edge on windows Microsoft Edge 40.15063.674.0 (Win 10)

**Comment by ossman** [comment]
That log shows a different host compared to the earlier one. `main3` in Firefox and `main3.mysender.ru` in Chromium. So I think this is just a misconfiguration. Please check your settings.

**Comment by CendioOssman** [comment]
That log shows a different host compared to the earlier one. `main3` in Firefox and `main3.mysender.ru` in Chromium. So I think this is just a misconfiguration. Please check your settings.

**Comment by CendioOssman** [comment]
No response from the original user. Closing.
