### ISSUE TITLE
Websocket token list doesn't play well with reverse proxy

### ISSUE THREAD

**Issue by lthrhx** [novnc/websockify#304]
NoVNC and apache reverse proxy for a single vnc server works fine:
Apache:
` ProxyPass /vnc http://cacti.cmslandbh.local:8787`
` ProxyPassReverse /vnc http://cacti.cmslandbh.local:8787`
` ProxyPass /websockify ws://cacti.cmslandbh.local:8787 retry=3`
` ProxyPassReverse /websockify ws://cacti.cmslandbh.local:8787`

In the terminal I start novnc:
`/var/www/html/novnc/utils/websockify/websockify.py --web /var/www/html/novnc 8787 scada:5900 &`

However if I would like to run another instance, I can't as websockify is hard-coded to look for example.com/websockify. I can rename example.com/vnc to example.com/notvnc or even example.com/subdirectory/whatisvnc and the page would load and it would work, as long as example.com/websockify was there. However example.com/websockify cannot be renamed or re-located. For example the following would not work (page loads, but can't connect to vnc host) even though a different port is used and can connect to it directly:

Apache:
`ProxyPass /directory/vnc http://cacti.cmslandbh.local:8686`
`ProxyPassReverse /directory/vnc http://cacti.cmslandbh.local:8686`
`ProxyPass /directory/websockify ws://cacti.cmslandbh.local:8686 retry=3`
`ProxyPassReverse /directory/websockify ws://cacti.cmslandbh.local:8686`

Since having multiple instances of novnc and websocket running didn't work I tried to go the token list route, but was unable to get websockify to work at all within a reverse proxy - even though it worked just fine using a single connection via terminal. Connecting directly to the server internally works as expected, but not through reverse proxy.

`/var/www/html/novnc/utils/websockify/websockify.py --web /var/www/html/novnc --target-config /var/www/html/novnc/token.list 8787 &`

Running Apache with the proxy  & proxy_wstunnel modules. 

I am not sure what logs are needed, so here are some screenshots of firefox output. 
Connecting directly to the novnc hosted server:
![successful](https://user-images.githubusercontent.com/32741474/31512625-a101d4d2-af59-11e7-8d98-45e908a38850.PNG)

Connecting through the proxy:
![error2](https://user-images.githubusercontent.com/32741474/31512626-a119bcf0-af59-11e7-9b44-62c2e0148e46.PNG)
![error1](https://user-images.githubusercontent.com/32741474/31512627-a12af38a-af59-11e7-942c-aac55ace14e5.PNG)

**Comment by CendioOssman** [comment]
It works just fine here. You have two issues:

 a) You should have `/websockify` in the target URL of the `ProxyPass` line as well.
 b) You've removed `/websockify` from the path you've given to noVNC. You should specify `vnc.html?path=%2Fwebsockify%3Ftoken%3Dscada`

**Comment by lthrhx** [comment]
Thank you. This is what my configuration looks like now and it works.

Apache:
`ProxyPass /virtdirectory/vnc http://cacti.cmslandbh.local:8686 retry=3`
`ProxyPassReverse /virtdirectory/vnc http://cacti.cmslandbh.local:8686`
`ProxyPass /virtdirectory/websockify ws://cacti.cmslandbh.local:8686/websockify retry=3`
`ProxyPassReverse /virtdirectory/websockify ws://cacti.cmslandbh.local:8686/websockify`

token.list contents:
`plus: desktop:5900`
`scada: client1:5900`

From terminal:
`/var/www/html/novnc/utils/websockify/websockify.py --web /var/www/html/novnc --target-config /var/www/html/novnc/token.list 8686 &`

From browser:
`http://example.com/virtdirectory/vnc/vnc.html?path=/virtdirectory/websockify?token=plus`
`http://example.com/virtdirectory/vnc/vnc.html?path=/virtdirectory/websockify?token=scada`

I am wrapping this all in SSL provided by apache so wss isn't needed. Virtdirectory is just a location within apache's config that I handle authentication, it works well with fail2ban.
