### ISSUE TITLE
How I can close websockify like Apache?

### ISSUE THREAD

**Issue by felix28** [novnc/websockify#305]
Hi, 

I want to ask how I can close and restart websockify using command like how it can be done in Apache?

Thanks

**Comment by CendioOssman** [comment]
I'm not sure what you mean. Are you referring to commands such as `service` and `systemctl`?

**Comment by felix28** [comment]
Yes. Anyways, I already created my custom commands.

For anyone who wants to close Websockify like Apache in Linux, you can do this:
fuser -k [yoursocketportnumber]/tcp

To view the status of Websockify like Apache in Linux, you can do this:
fuser [yoursocketportnumber]/tcp

**Comment by CendioOssman** [comment]
I'm afraid any kind of service handling is not something that websockify has. Right now it's just a command to run. If you need services then you'll have to write some wrappers on your own.
