### ISSUE TITLE
Update Wiki to Reflect Windows Not Supported

### ISSUE THREAD

**Issue by mtayl0r** [novnc/websockify#309]
This project (websockify) is the second result when googling for "websocket proxy windows", and Windows isn't supported. The wiki really ought to be updated to reflect this, specifically this page[1] needs to be removed. Indeed, all Windows references should be removed except to say Windows isn't supported. Wasted my afternoon, and many others have as well I wager.

[1] https://github.com/novnc/websockify/wiki/Compiling-Websockify-as-Windows-Executable

**Comment by samhed** [comment]
I generally agree with you. One complicating factor here is that occasionally we get stray reports from people who successfully use it on Windows.

A quick search suggests that the node.js version of websockify works on Windows:

https://github.com/novnc/novnc/issues/807#issuecomment-292285115

It's not something I have tested myself though. Generally this is a grey area and I don't believe that any of us maintainers have much interest in Windows.

**Comment by mtayl0r** [comment]
I would not call it a "grey area" since there is now code in the project that _specifically prohibits_ it from running under windows. At the very least, could the windows related pages be updated to reflect using the node version inplace of the python version?

https://barkingbogart.wordpress.com/2014/10/08/use-websockify-in-windows/

**Comment by CendioOssman** [comment]
Anyone should be able to poke around in the wiki, so feel free to adjust things.

**Comment by samhed** [comment]
https://github.com/novnc/websockify/issues/67#issuecomment-354792644

**Comment by JIBSIL** [comment]
Use node-websockify! 
https://www.npmjs.com/package/node-websockify
God,   took me   so long to find that.

**Comment by samhed** [comment]
Windows support is enabled again as of #388
