### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by jeffforbes** [novnc/websockify#315]
We have a system using websockify/novnc that has work perfectly for well over a year. Recently the websockify connection stopped working. There have been no updates to the software. 

The javascript error is:
connecting to wss://abcdef.com:8080/?token=BF3BE0B1
util.js:216 Detected binaryType support in WebSockets
VM398:164 WebSocket connection to 'wss://abcdef.com:8080/?token=BF3BE0B1' failed: Error in connection establishment: net::ERR_CONNECTION_RESET
WrappedWebSocket @ VM398:164
util.js:218 WebSocket on-error event
Util.Warn @ util.js:218
util.js:218 WebSocket on-close event
Util.Warn @ util.js:218
util.js:220  Msg: Server disconnected (code: 1006)

The python traceback was:
2017-11-15 13:00:22,401 handler exception: (104, 'Connection reset by peer')
2017-11-15 13:00:22,401 exception
Traceback (most recent call last):
  File "/opt/websockify/websocket.py", line 925, in top_new_client
    client = self.do_handshake(startsock, address)
  File "/opt/websockify/websocket.py", line 811, in do_handshake
    handshake = sock.recv(1024, socket.MSG_PEEK)
error: (104, 'Connection reset by peer')

We have restarted the websockify server and the  computer that is is running on.
tcpdump shows the connection from the browser and the response packet is a RST

Does anyone have any suggestions of where to look for the cause of this issue?

**Comment by CendioOssman** [comment]
This looks like a network issue as both sides are getting a network reset. Perhaps a firewall that has decided to start blocking things?

**Comment by CendioOssman** [comment]
No response. Closing.
