### ISSUE TITLE
How to connect to mystic bbs?

### ISSUE THREAD

**Issue by ryanfantus** [novnc/websockify#316]
Hey, I've been trying to get websockify to allow me to connect to a locally hosted mystic bbs. Mystic runs a server daemon (currently bound to port 2323). I launched websockify like so:
`sudo websockify --cert=/etc/letsencrypt/live/<domain>/fullchain.pem --key=/etc/letsencrypt/live/<domain>/privkey.pem --ssl-only --wrap-mode=respawn 7003 localhost:2323`

I then try to configure wstelnet.html to hit my domain, port 7003. When I try to connect, I keep getting the following errors:

`<my_local_domain> - - [29/Nov/2017 01:58:45] code 400, message Client must support 'binary' or 'base64' protocol
<my_local_domain> - - [29/Nov/2017 01:58:45] code 405, message Method Not Allowed
`

No matter what I do I can't seem to get around these two errors. I've also tried using VTXClient to connect, and I receive the same exact error. Please advise. Thanks!

**Comment by CendioOssman** [comment]
It looks like your websockify is a bit old. Can you try the latest commit and see if that works?

**Comment by ryanfantus** [comment]
Yep! Thanks. 

Also, I am now using nginx to terminate ssl proxy traffic from :7003 to :7004. I am trying to use websockify to bridge :7004 to :2323 (basically just connect to mystic bbs's listener on that port).

Grabbed the latest and now am just getting

`localhost - - [30/Nov/2017 04:13:39] code 400, message Invalid protocol selected`

**Comment by ryanfantus** [comment]
Disregard, figured it out. The client I was using to initiate connections was failing to pass 'binary' - had to modify the source since it isn't currently configurable. Thanks for the help!

**Comment by CendioOssman** [comment]
It should be possible to also omit the protocol. However it will deny you if you specify some other protocol.
