### ISSUE TITLE
Ping from client to server

### ISSUE THREAD

**Issue by brospars** [novnc/websockify#318]
Hi,
Sorry if post on the wrong repository but my problem is both on the server and client side.
I'm using novnc to stream some app and I would like to benchmark the quality of the client connection. So I capture some metrics but the one I can't figure out is how to send a ping request to the server from the client. Is it even possible ?
I saw there is standard for ping/pong ([RFC 6455](https://tools.ietf.org/html/rfc6455#section-5.5.1)) and that websockify implements [this](https://github.com/novnc/websockify/blob/6b1d42e643f82870cbd7aabd95b3c743ba7d3f54/websockify/websocket.py#L619) but I have no idea how to send it using javascript.

Some help would be great. Thanks.

**Comment by brospars** [comment]
Ok thanks. I was hoping for a way to send a custom frame with the right `opcode` like [here](https://github.com/websockets/ws/blob/master/lib/Sender.js#L177). I'll try and post my solution here.

**Comment by CendioOssman** [comment]
Yeah, that is possible if you are running in an environment with raw sockets (i.e. not browsers).

**Comment by brospars** [comment]
I see.. I'll find another way then.

Thanks a lot.
