### ISSUE TITLE
How to enable TLS certificate

### ISSUE THREAD

**Issue by samgoud** [novnc/websockify#319]
Hi, 
I am using the default option from novnc while running utils/launch.sh script. 
The process I see is 
sambadda  5243 14748  0 Dec12   00:00:00 python /kanaka-noVNC-tigerVNC/utils/websockify/run --web /kanaka-noVNC-tigerVNC/utils/../ --cert /kanaka-noVNC-tigerVNC/utils/self.pem 6080 localhost:5965

My company prohibits use of SSL v3 and asked me to switch to TLS 1.2.

Can you please help me how to achieve this.

**Comment by CendioOssman** [comment]
That command line looks correct. What problem are you seeing?

**Comment by samgoud** [comment]
I do not have any issues in launching my vnc server in webpage using novnc as above.
What I want is noVnc to use TLS 1.2 encryption. Looks like currently it is using SSL v3 as encryption by default. How do I configure noVNC to enable and use TLS 1.2 encryption.

**Comment by samgoud** [comment]
I basically want to disable SSL v3 and only enable TLS v1 and above on server side.
For example in apache putting "SSLProtocol All -SSLv2 -SSLv3" in the configuration file disables sslv3.
How do I achieve something similar with noVNC ?

**Comment by CendioOssman** [comment]
Ah, I see. We don't have way to give similar flags. However we did recently add 914609fb5f1df31e9ecd27ad73ceda035357cecb and #190, which suggests that you should not get SSL3 as long as your Python is new enough.
