### ISSUE TITLE
Unable to make a https connection with certificate

### ISSUE THREAD

**Issue by samgoud** [novnc/websockify#320]
Hi,
I have a certificate (cert.pem) issue by my organization certification authority. I have passed this certificate with --cert option to novnc utils/launch.sh script. When I use the novnc given https url in browser, it displays the error "This site cant be reached" with error code "ERROR_CONNECTION_CLOSED".
The logs on the novnc terminal shows the following errors:

```
handler exception: [Errno 336265225] _ssl.c:339: error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib
handler exception: [Errno 336265225] _ssl.c:339: error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib
handler exception: [Errno 336265225] _ssl.c:339: error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib
handler exception: [Errno 336265225] _ssl.c:339: error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib
9.77.xxx.xxx: ignoring empty handshake
handler exception: [Errno 336265225] _ssl.c:339: error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib
9.77.xxx.xxx: ignoring empty handshake
```

**Comment by CendioOssman** [comment]
I seem to recall that error being seen when it cannot read the private key.

Have you checked the permission of the key file?

Does the key have a password set for it? That is unfortunately not supported.

**Comment by samhed** [comment]
No response
