### ISSUE TITLE
Keyboard input stops working after pressing ALT (Gr) with Firefox Quantum

### ISSUE THREAD

**Issue by sonicnkt** [novnc/websockify#322]
Hi,
i noticed that keyboard input (letters and numbers only, backspace and enter still work) after i press the Right Alt key. i have an @ symbol in my password and with a german keyboard layout you have to press ALT-GR + Q to creat this symbol.
VNC Password works fine btw, im talking about entering this symbol after a connection is established (windows password in my case)

But like i said after i the symbol is added cant input anything else until i reload the the complete page and connect again. 

Cant test it with another browser atm because chromium refuses to load the novnc page at all with my current test setup. Maybe this is a firefox related problem but i thought i ask if someone else experiences this.

Nils

**Comment by CendioOssman** [comment]
I'm afraid you're in the wrong repository. This is for the proxy service, not noVNC. Could you please file this again under the noVNC repository. Please also include which version or commit of noVNC you are using.

**Comment by sonicnkt** [comment]
ah sorry, had several tabs open and posted in the wrong one!
