### ISSUE TITLE
Does the launch of kanaka noVNC create a socket under /tmp/.X11-unix?

### ISSUE THREAD

**Issue by joynexa** [novnc/websockify#325]
Does the launch of kanaka noVNC create a socket under /**tmp/.X11-unix** or any other folder ? 

A sample command execution is:
../novnc/utils/launch.sh  --vnc localhost:**5901** --listen **6080** &

I find that socket **X1** is created in **/tmp/.X11-unix** ..Similarily is there a file/folder created for **6080** anywhere so that I can keep a track of websockify ports in use.

Thanks ..

**Comment by CendioOssman** [comment]
> Does the launch of kanaka noVNC create a socket under /tmp/.X11-unix or any other folder ?

No. websockify does not create any Unix sockets anywhere. That folder is used by your X servers, and you've most likely also started a VNC server that opened a Unix socket there.

> Similarily is there a file/folder created for 6080 anywhere so that I can keep a track of websockify ports in use.

No. TCP sockets are not represented in the file system. Use `ss` to examine which sockets are in use on your system.

**Comment by joynexa** [comment]
Thank you ..
When I try to launch a vncserver now at display port **:80**,( **vncserver :80** ) it throws up a message saying **Port already in use**. Are the TCP ports and Xserver ports overlapping in nature?

Does it prevent me from executing something like :
**../novnc/utils/launch.sh --vnc localhost:5980 --listen 6080 &**

Thanks
