### ISSUE TITLE
noVnc/Websockify locking up display port 

### ISSUE THREAD

**Issue by samgoud** [novnc/websockify#326]
Hi, 
I am running noVnc as below
utils/launch.sh --vnc localhost:5964 --listen 6080

After the above step, I see display ports :80 and :180 are both locked up. When I run the vncserver on these displays, I see "vnc already running" error
$:> vncserver  :180
A VNC server is already running as :180
$:> vncserver  :80
A VNC server is already running as :80

If I kill the launch.sh process, I am to create the vnc server at display :180 and :80.

locking 180 display is expected as it corresponds to 6080, but why is noVnc locking the 80 ?

**Comment by CendioOssman** [comment]
X11 uses a port allocation strategy of `6000 + display`. So display :80 would be port 6080, which you just allocated for websockify. So you'll have to avoid such overlap.

**Comment by samgoud** [comment]
Thanks for the response.
Doing a netstat on the ports confirmed xvnc takes up two ports 5900+N and 6000+N where N is display.
