### ISSUE TITLE
Limit on the number of TCP ports that can be used

### ISSUE THREAD

**Issue by joynexa** [novnc/websockify#328]
Here  is the sample command we execute in the shell to launch noVNC ..
**../novnc/utils/launch.sh --vnc localhost:5901 --listen 6080 &**

1. Is there a restriction on the port number used as an argument to **--listen**? Is it mandated that we start from 6080?
2. What is the limit on the number of active TCP ports that can be listened to on a Unix machine? Is there a cap of 100?
3. Are the following --listen arguements one and the same..(6080 and 7080)?
../novnc/utils/launch.sh --vnc localhost:5901 --listen 6080 &**
**../novnc/utils/launch.sh --vnc localhost:5901 --listen 7080 &

4. Usage of a TCP port(say 6080), Does it prevent a vncserver from launching on DISPLAY port( say 80)?

Thanks ..

**Comment by CendioOssman** [comment]
> 1. Is there a restriction on the port number used as an argument to --listen? Is it mandated that we start from 6080?
> 

No, you can use any port you want.

>  2.  What is the limit on the number of active TCP ports that can be listened to on a Unix machine? Is there a cap of 100?
> 

No, most system will most likely allow all the 65535 ports that TCP defines.

>  3.  Are the following --listen arguements one and the same..(6080 and 7080)?
>     ../novnc/utils/launch.sh --vnc localhost:5901 --listen 6080 &**
>     **../novnc/utils/launch.sh --vnc localhost:5901 --listen 7080 &
> 

Not sure what you are asking here. Those two lines would start a websockify server on two different ports.

>  4.  Usage of a TCP port(say 6080), Does it prevent a vncserver from launching on DISPLAY port( say 80)?

Yes, as you asked in #326.

**Comment by joynexa** [comment]
Thank you !!
