### ISSUE TITLE
100% CPU load before first access

### ISSUE THREAD

**Issue by rkarlsba** [novnc/websockify#330]
Hi

I have a bunch of raspberry pi's for controlling infoscreens. These work well, and to help central monitoring, they also run websockify to allow for novnc connections. This also works, but… It seems that after a reboot, whatever caused it, websockify uses 100% CPU on all cores until accessed on the net. After the first access from a browser, which works, everything else works well and CPU load drops to normal. When running strace -fp while it's running on 100%, this is what it does, all the time

[pid 1354] <... gettimeofday resumed> {1518703139, 289353}, NULL) = 0
[pid 1355] gettimeofday( <unfinished ...>
[pid 1353] gettimeofday( <unfinished ...>
[pid 1355] <... gettimeofday resumed> {1518703139, 289411}, NULL) = 0
[pid 1353] <... gettimeofday resumed> {1518703139, 289437}, NULL) = 0
[pid 1354] gettimeofday( <unfinished ...>
[pid 1353] gettimeofday( <unfinished ...>
[pid 1355] gettimeofday( <unfinished ...>
[pid 1353] <... gettimeofday resumed> {1518703139, 289541}, NULL) = 0
[pid 1355] <... gettimeofday resumed> {1518703139, 289558}, NULL) = 0
[pid 1354] <... gettimeofday resumed> {1518703139, 289588}, NULL) = 0
[pid 1353] gettimeofday( <unfinished ...>
[pid 1355] gettimeofday( <unfinished ...>
[pid 1354] gettimeofday( <unfinished ...>
[pid 1355] <... gettimeofday resumed> {1518703139, 289684}, NULL) = 0
[pid 1354] <... gettimeofday resumed> {1518703139, 289729}, NULL) = 0
[pid 1355] gettimeofday( <unfinished ...>
[pid 1353] <... gettimeofday resumed> {1518703139, 289663}, NULL) = 0
[pid 1355] <... gettimeofday resumed> {1518703139, 289793}, NULL) = 0

After visiting nosql and then closing the browser, it goes back to what looks normal (or where it should have been in the first place)

[pid 1563] recv(4, "\210\202\2269n\214\225\320", 4096, 0) = 8
[pid 1563] send(4, "\210\0", 2, 0) = 2
[pid 1563] shutdown(7, SHUT_RDWR) = 0
[pid 1563] close(7) = 0
[pid 1563] exit_group(0) = ?
[pid 1563] +++ exited with 0 +++
<... select resumed> ) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1563, si_uid=1000, si_status=0, si_utime=13, si_stime=6} ---
sigreturn() (mask []) = -1 EINTR (Interrupted system call)
wait4(1563, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 1563
gettimeofday({1518703147, 631963}, NULL) = 0
select(4, [3], [], [], {1, 0}) = 0 (Timeout)
gettimeofday({1518703148, 633782}, NULL) = 0
select(4, [3], [], [], {1, 0}) = 0 (Timeout)
gettimeofday({1518703149, 635654}, NULL) = 0
select(4, [3], [], [], {1, 0}) = 0 (Timeout)
gettimeofday({1518703150, 637354}, NULL) = 0
select(4, [3], [], [], {1, 0}) = 0 (Timeout)
gettimeofday({1518703151, 638865}, NULL) = 0
select(4, [3], [], [], {1, 0}) = 0 (Timeout)
gettimeofday({1518703152, 640382}, NULL) = 0
select(4, [3], [], [], {1, 0}) = 0 (Timeout)
gettimeofday({1518703153, 642039}, NULL) = 0
select(4, [3], [], [], {1, 0}) = 0 (Timeout)
gettimeofday({1518703154, 643825}, NULL) = 0
select(4, [3], [], [], {1, 0}) = 0 (Timeout)
gettimeofday({1518703155, 645688}, NULL) = 0
select(4, [3], [], [], {1, 0}^CProcess 1303 detached

I'm using a git version from october or thereabouts. I tried with the latest, and the problem persists.

**Comment by CendioOssman** [comment]
We did have a 100% CPU issue recently, but that did not manifest in this way. So first I'd like you to see if you get the same strace output with the current `master`.

How are you starting websockify?

**Comment by rkarlsba** [comment]
Below is how I started it

hioa@sg29-sg215-infopi1:~/strace $ strace -f -o strace.1 python /usr/local/noVNC/utils/websockify/run --web /usr/local/noVNC [::]:6080 [::1]:5900
WebSocket server settings:
  - Listen on :::6080
  - Web server. Web root: /usr/local/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :::6080 to ::1:5900
^CIn exit

The two versions behave the same. The load websockify doesn't use so much while the strace is running, but then, strace uses a lot. websockify uses just as much or little if I start it with strace or attach strace to it later. I the latter example, if I detach, the load is back on 100% per core - that is - with the latest version - it seems to be at 100% on three, not four cores. Not sure about why. See before/after strace files below.

[strace.zip](https://github.com/novnc/websockify/files/1731226/strace.zip)

**Comment by CendioOssman** [comment]
So I compared with my system here (Fedora 27), and I'm getting something similar with two extra threads being started. However they call `sched_yield()` repeatedly rather than `gettimeofday()`. They also calm down shortly after startup.

I used gdb and found that these threads are started by numpy/libopenblas. From your strace log, the same seem to be the case for your system. So I'm afraid it seems like numpy (or Python) is somehow broken on your system. You could try uninstalling numpy as it is not a hard requirement for websockify, but it will slow things down. Other than that I'm afraid I'll have to direct you to report a bug with your distribution. :/

**Comment by rkarlsba** [comment]
Well, these don't calm down after startup, unless you're counting hours/days as 'shortly'. Also, I'm not sure how this can be numpy's fault since after the initial connection to them from a browser, they start. behaving correctly.

**Comment by CendioOssman** [comment]
I agree that it is a bit weird that gets them to calm down. But the reality is that websockify doesn't start a single extra thread, so the bug is at least not here. Numpy seems to be the owner of those threads so the best guess as to who can fix this bug.

**Comment by rkarlsba** [comment]
Thanks - old jessie here, and I don't have time for an upgrade of all these, even with ansible, so I tried removing numpy, and it solved the problem.

What does it use numpy for in the first place?

**Comment by CendioOssman** [comment]
All WebSocket traffic requires some obfuscation using XOR, and numpy is used to apply and remove that obfuscation. So without numpy you'll get higher CPU usage for any traffic flowing through websockify. I'm afraid I don't have any numbers exactly how much more.
