### ISSUE TITLE
Trying to connect getting error.

### ISSUE THREAD

**Issue by ThLoser** [novnc/websockify#335]
When im trying to connect to my own irc server i get this error: 
"SecurityError: The operation is insecure. (websock.js,227)"

**Comment by CendioOssman** [comment]
Are you trying to use a non-TLS WebSocket connection on a TLS page? I.e. using `ws://` with a `https://` page? Browsers don't generally allow that, so you need to use `wss://`.

**Comment by ThLoser** [comment]
Yeah i did that and changed to wss but got a new error then

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by CendioOssman** [comment]
And that error was?

**Comment by ThLoser** [comment]
Thats a good question ???? im at work now i can send u that error tonight when im home again

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by ThLoser** [comment]
Hello sir! Im sorry for this late answer.



When im trying to connect now with SSL i get error Firefox can not establish a connection to the server at wss: //127.0.0.1: 6697


________________________________
Från: Pierre Ossman (Work account) <notifications@github.com>
Skickat: den 12 mars 2018 13:34
Till: novnc/websockify
Kopia: ThLoser; Author
Ämne: Re: [novnc/websockify] Trying to connect getting error. (#335)


And that error was?

**Comment by ThLoser** [comment]
I found something that can make it shit.. When im connecting trough mIRC with the SSL port i need to have a "+" infront of the port, or i get disconnected. And i can't connect with + in the wsirc.html


________________________________
Från: Pierre Ossman (Work account) <notifications@github.com>
Skickat: den 12 mars 2018 13:34
Till: novnc/websockify
Kopia: ThLoser; Author
Ämne: Re: [novnc/websockify] Trying to connect getting error. (#335)


And that error was?

**Comment by CendioOssman** [comment]
Hmm... Are you connecting directly to the IRC server from wsirc.html? The host and port there need to be the host and port of your websockify proxy, not your irc server.

**Comment by ThLoser** [comment]
Then we found the error im trying to connect to irc

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________
