### ISSUE TITLE
how to connect to running server

### ISSUE THREAD

**Issue by pidloop** [novnc/websockify#336]
Hello,

First: this is great work, many thanks. I will make a donation to H_for_H as requested.

I have succeeded using **run** making a web page that connects to a toy server started by run.

But what I need is a way to make a new socket connection to a long-running daemon server that is already running. Is there a way to do this?

**Comment by CendioOssman** [comment]
I'm afraid I don't understand. There is no real difference between connecting to a newly started server and an already running one.

Exactly what are you trying to do with websockify?

**Comment by pidloop** [comment]
Hi. The example gives "./run 2023 -- PROGRAM ARGS" which runs PROGRAM each time a page arrives. This works fine for a toy PROGRAM I wrote. But what I really want is for PROGRAM to be already running on a known server port, I just want to connect to it each time.

**Comment by CendioOssman** [comment]
Ah. Then you run:

```
./run 2023 SERVER:PORT
```

`SERVER` will be `127.0.0.1` if it's on the same machine.
