### ISSUE TITLE
numpy is listed in setup.py as a requirement but isn't really a requirement

### ISSUE THREAD

**Issue by josedpedroso** [novnc/websockify#337]
I had to install websockify on my OpenWRT router, but that failed when it tried to build numpy. Looking at the code, numpy is optional. I removed numpy from install_requires in setup.py and it installed and runs fine.

From https://packaging.python.org/discussions/install-requires-vs-requirements/

> install_requires is a setuptools setup.py keyword that should be used to specify what a project **minimally** needs to run correctly.

**Comment by kanaka** [comment]
Unfortunately very few package managers have the concept of "optional but default" (i.e. always installed unless the user explicitly disallows it). Numpy is needed by websockify to avoid reduced performance so we want it to always be installed with websockify except in rare situations (like yours) where there is some desire or need to avoid numpy. This has come up before (although only one other time that I recall). If we wanted to officially support this scenario (and I'm not convinced we do), my inclination would be to have an alternate websockify package (i.e. websockify-minimal or something like that).

**Comment by josedpedroso** [comment]
You should at least mention in the readme that numpy isn't really required, then. But IMHO the warning about reduced performance when starting websockify without numpy would be enough.
