### ISSUE TITLE
Web Sockify connexion simulated in JMeter

### ISSUE THREAD

**Issue by Barbeblanche** [novnc/websockify#345]
Hi ! I'm trying to reproduce websockify connexion between a client and a noVNC server with a password.
I have analyses VNC frame data, and I think I found the password frame but the data of this frame always change. If you can help me on the encryption of the password or the RFB protocol, I will be very grateful.

**Comment by CendioOssman** [comment]
The protocol is described here:

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst

The password encryption is detailed in this section:

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#vnc-authentication
