### ISSUE TITLE
Error when using websockify?token=something

### ISSUE THREAD

**Issue by Cuningan** [novnc/websockify#347]
HEllo i have a issue with chrome, the variable token is used by google chrome and when used by us breaks chrome Java Session.
I think we need to change the name to other.

**Comment by Cuningan** [comment]
hello.

I manage to change 'token' to other word and now it seems to work ok in Google Chrome.

**Comment by Cuningan** [comment]
Hello, normal setup, noVNC in Chrome and websockify in Oracle Linux.
I have wrote my own token plugging that send me a jsessionid and based on that I forward to one or other Uvnc server.
But the token get modified by Chrome and the webpage developer said me that token is a reserved word in Chrome.
I manage to change "token" to other and problem gone.

**Comment by samhed** [comment]
No response
