### ISSUE TITLE
multiple users at same time with different instance

### ISSUE THREAD

**Issue by suneel11** [novnc/websockify#350]
Hello,
I am trying to provide a different access of the noVNC screen, but I am all getting the already logged in user / single instance. I just need multiple users can access there own window at the same time. Such that one user cannot enhance the working the other user.
Is there any way in websockify which can help me to create different instance for the multiple users in the noVNC. 
If there is any way out then please let me know so that I can complete my task.

**Comment by samhed** [comment]
Can you stop posting the same question multiple times.

https://github.com/novnc/noVNC/issues/1072

**Comment by suneel11** [comment]
Sorry for that but I am not getting any idea for how I can solve this issue. That's why I have generated the issue again with webshockify for the help.
I have tried many things to solve this issue but I am not getting any way out.

**Comment by suneel11** [comment]
Almost things are done except this issue. Please have a look the video for the reference. 
(https://r3---sn-qxa7sn7r.c.mail.google.com/videoplayback?id=6ca96078abb3f230&itag=18&source=webdrive&requiressl=yes&mm=30&mn=sn-qxa7sn7r&ms=nxu&mv=u&pl=24&ttl=transient&ei=IE3sWtHECM30ugXbl73ACg&susc=dr&driveid=1dnNgfcQNyW9B6dOUKgfER-TEQZUWAPeD&app=explorer&mime=video/mp4&lmt=1520928416319555&mt=1525434836&ip=122.160.12.75&ipbits=0&expire=1525439280&cp=QVNHV0VfWFJWQVhOOjhscFU3QnpNa0RW&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,ttl,ei,susc,driveid,app,mime,lmt,cp&signature=B4BBDD17356CFF8EA0AD14EE1EBCB499145CF1C7.9D94D0528FEC1F4AE6A04B53F61EBF29127852A2&key=ck2&cpn=nzAkqta1Xt25OrGm&c=WEB_EMBEDDED_PLAYER&cver=20180503)
The reference site is using multiuser with noVNC. That's why I need your valuable suggestion to implement multiuser functionality for remote system access. Please share your valuable thoughts :). 

Thank you in advance...

**Comment by CendioOssman** [comment]
I'm afraid that link doesn't work.

But that doesn't really matter. Neither websockify nor noVNC tries to handle the case of how to set up and manage multiple sessions. This is something you will have to get help with elsewhere.

**Comment by Priyanka12345678910** [comment]
@suneel11  Did you get the solution to this issue ? I am also facing the same.

**Comment by suneel11** [comment]
sorry for that but I didn't get any solution till. I am still looking for the better solution.
