### ISSUE TITLE
Request: ability to limit SSL to TLS1.2 (and above) only

### ISSUE THREAD

**Issue by mykaul** [novnc/websockify#352]
Currently, there doesn't seem to be a way to limit the negotiated ciphers and friends to TLS 1.2 and above. 
It'd be great if there was some way to pass this configuration option to websockify (I'm referring mainly to the Python implementation, but surely all can benefit from it).

**Comment by tomob** [comment]
There's a PR for that:
https://github.com/novnc/websockify/pull/355

**Comment by samhed** [comment]
This was fixed with #355
