### ISSUE TITLE
Support using VNC SSL between WS proxy and host

### ISSUE THREAD

**Issue by twhitehead** [novnc/websockify#354]
Would be nice if something like this patch (for the openstack websocket proxy) could be included

https://review.openstack.org/#/c/77266/
https://review.openstack.org/#/c/77266/5/nova/console/websocketproxy.py

to allow end-to-end encryption when using noVNC with websockify.

Thanks!  -Tyson

**Comment by CendioOssman** [comment]
I'm afraid that adds a bit too much complexity than we want in websockify. It's just supposed to be a simple example/base after all.
