### ISSUE TITLE
[Question] Can websockify handle multiple clients on demand? 

### ISSUE THREAD

**Issue by al3x609** [novnc/websockify#361]
my configuration use, websockify/novnc/ngnx, over the same server, in a second server, multiple user by ssh terminal deploy multiple vnc instances. 

Im new with websockify, How can I face this scheme?
 Can a single instance work with this o I should be deploy multiple websockify instances?

**Comment by CendioOssman** [comment]
You can use the token system for this:

https://github.com/novnc/websockify/wiki/Token-based-target-selection

Each VNC server would then be reachable using individual URLs.
