### ISSUE TITLE
using .cert,.ca-bundle and a .key file

### ISSUE THREAD

**Issue by kpetrow** [novnc/websockify#363]
Hi,
Im trying to run wss to server that is using https.  i ahve a .cert file and a .key file I generated from IIS by using pfx export then ripping the .key file out of that using an online tool.  I also have a .ca-bundle file.

I specifiy websockify to run pointing to the cert = ..../file.cert and key = '..../file.key'  websockify start but i get a "net::ERR_SSL_PROTOCOL_ERROR" when trying to connect through NoVnc.

Am i supposed to concat the cert and .ca files?  does this include the headers?

thanks

**Comment by CendioOssman** [comment]
Yes. But I think it can be upset about the order. Have you tried switching it?

**Comment by samhed** [comment]
No response
