### ISSUE TITLE
TLS support for target connection

### ISSUE THREAD

**Issue by ssup2** [novnc/websockify#366]
Hi. 
I want to websockify connect to source addr, source port with SSL/TLS.
But websockify doesn't seem to support this.

Is there any plan for this?

**Comment by CendioOssman** [comment]
I assume you mean the target and not the source? The source are for the incoming WebSocket requests, and that side has TLS support.

But the target side does indeed not. It's just a simple TCP connection without any special handling. I don't think anyone is working on it, but it should be possible to add. The difficult part is probably getting the certificate verification working properly.

**Comment by ssup2** [comment]
Oops. Target is right. If there is nobody working this, I want to contribute to this. Thanks.

**Comment by CendioOssman** [comment]
Great. Contributions are always welcome. Feel free to open a pull request when you have something and we can look at the details there.

**Comment by ssup2** [comment]
I find --ssl-target option today because there is no --ssl-target option info in man. And I try to connect to ssl-server with --ssl-target and it works well.
