### ISSUE TITLE
[Question] Can I change the tcp payload when I'm using tcp proxy on two different machine between Client and Server??

### ISSUE THREAD

**Issue by PraveenKumarSoni** [novnc/websockify#367]
Actually, I want to encrypt the communication between to client and server by using Machine A & Machine B. And communication between Machine A and Machine B should be in TLS protocol by using SSL Socket. 

Please suggest me.

**Comment by CendioOssman** [comment]
I'm afraid I don't quite understand the question. If machine A is the browser, and machine B is websockify, then using TLS is possible. Specify `--cert` and `--key` and TLS will be enabled.

Is that what you are after?

**Comment by PraveenKumarSoni** [comment]
Ok, I'm explaining it in detail:
                     
                          Server    <--->     Machine_B    <--->     Machine_A     <--->      Client

Through this route Client will send TCP data to the Machine_A and Machine_B will receive data from Machine_A and now Machine_B will send data again to the Server. And communication between Machine_A and Machine_B should in TLS protocol. 
Through this, I'm trying to encrypt the communication between Server and Client by using two machines(Machine_A and Machine_B).

Please suggest me how can I do this.

**Comment by CendioOssman** [comment]
This has nothing to do with websockify. I would suggest some general Python discussion forum for helping you get your code working.
