### ISSUE TITLE
New pip package release

### ISSUE THREAD

**Issue by trevor** [novnc/websockify#368]
Would it be possible to release a new pip package for websockify?

The current version on PyPI is 0.8.0, released in Feb 2016. There have been several bug fixes since then I'd like to deploy by using an official package.

**Comment by CendioOssman** [comment]
Yeah, we should look at getting some new release out. We're trying to do a repo split before that though.

#360 is basically the same issue, but for the JavaScript parts.

@kanaka, how are pip packages updated? Is that something only you have access to?

**Comment by kanaka** [comment]
@CendioOssman I can add you as an owner of the websockify package on pypi.org. I just need to know your pypi username.

**Comment by CendioOssman** [comment]
I've created the account "CendioOssman" now. So please add that. :)

**Comment by kanaka** [comment]
@CendioOssman okay, you've been added as one of the owners of the project.

**Comment by atz** [comment]
Can we start by just getting some git tags for more recent repo release states that are known to be in good working order?

**Comment by Hyask** [comment]
@CendioOssman has this issue made any progress?

**Comment by CendioOssman** [comment]
No, I'm afraid not. My plan was to make a go at #362 and then tag a new development release after that.

**Comment by Hyask** [comment]
Oh, that's a pity. And I suppose the changes are too important to simply bump the `patch`, making a `0.8.1` release?

**Comment by CendioOssman** [comment]
Alright, so a new version is now up here on github and on pypi. :)
