### ISSUE TITLE
Windows is not supported at this time

### ISSUE THREAD

**Issue by quzefeng** [novnc/websockify#370]
E:\other\novnc\websockify-master\dist>run.exe 5901 localhost:5900
E:\other\novnc\websockify-master\dist\library.zip\websockify\websocket.py:30: UserWarning: no 'numpy' module, HyBi protocol will be slower
WARNING: no 'resource' module, daemonizing is disabled
Windows is not supported at this time

i have this error, please help me,thanks;

**Comment by CendioOssman** [comment]
As the error states, Windows is not supported at this time. See issue #67.
