### ISSUE TITLE
Disable DES cipher for python-websockify (i.e. on port 6080)

### ISSUE THREAD

**Issue by Priyanka12345678910** [novnc/websockify#373]
On running the below command, 3DES cipher is resulted with the least strength i.e. C.

nmap --script ssl-enum-ciphers -p 6080 hostname

On the same host DES is disabled for port 443. So it seems for nginx it has been taken care but for python-websockify it is still present.

So in brief I am finding the way to disable the 3DES cipher on port 6080 of the host. Thanks in advance.

**Comment by CendioOssman** [comment]
We have the argument `--ssl-ciphers` that you can give to websockify. It is an OpenSSL cipher string where you can enable and disable things as you please. I'm afraid I don't know the specifics of it off hand, so please see their documentation for how this string works.
