### ISSUE TITLE
Can I ask websockify to choose and bind a source port for me?

### ISSUE THREAD

**Issue by shaioz** [novnc/websockify#375]
Hi, I'm running multiple instances of Websockify on a server which has many sockets opening and closing. We think we have a bug where we pick a random open port and call websockify and by the time it happens the port may be already used. Can I somehow call Websockify so that it bind(0) and prints to me the chosen port?

Thanks

**Comment by CendioOssman** [comment]
No, I'm afraid that is not something we have right now. You have to specify a fixed port before you launch it.
