### ISSUE TITLE
Multiple VNC tokens

### ISSUE THREAD

**Issue by imatrycode** [novnc/websockify#378]
Having an issue with the token system via websockify

I have started websockify using tokens and have set my token directory the only way I can get it work is using the same url then on the url changing the websockify path in the connect dialog

Is there any way the url can be used to connect

E.g.

Https://domain/novnc.html?token=example&port=xxx&password=blah

To go directly to the vnc session based on url with the token in the url

**Comment by CendioOssman** [comment]
This is really a noVNC question, but yes you can modify the path directly from the URL. E.g.

https://example.com/novnc.html?path=websockify%3Ftoken%3Dexample

The key is replacing the embedded `?` with `%3F` and the embedded `=` with `%3D`.

**Comment by imatrycode** [comment]
Thanks yeh that works fine the key is modifying the path , makes sense , thank you
