### ISSUE TITLE
Error reporting when launching.sh is executed

### ISSUE THREAD

**Issue by bj-white** [novnc/websockify#379]
[root@world noVNC]# ./utils/launch.sh --vnc 192.168.1.10:5900
No installed websockify, attempting to clone websockify...
Initialized empty Git repository in /root/noVNC/utils/websockify/.git/
**error: while accessing https://github.com/novnc/websockify/info/refs**

fatal: HTTP request failed
Unable to locate /root/noVNC/utils/websockify/run after downloading

**Comment by samhed** [comment]
Seems like you can't access the github repo for some reason. Does this "world" machine have internet access?

**Comment by bj-white** [comment]
Yes, I can surf the Internet. noVNC downloaded it from github.

**Comment by bj-white** [comment]
error:  while accessing https://github.com/novnc/websockify/info/refs
Is it because there is no "info" file?

**Comment by samhed** [comment]
Searching on google indicates that this issue might happen if you are using an ancient version of git. What version do you have?
