### ISSUE TITLE
Allow passing passphrase for cert file

### ISSUE THREAD

**Issue by Nevon** [novnc/websockify#381]
Trying to run websockify with an encrypted private key leads to Python trying to interactively get the password:

```
websockify_1  | /opt/websockify/websockify/websocket.py:30: UserWarning: no 'numpy' module, HyBi protocol will be slower
websockify_1  |   warnings.warn("no 'numpy' module, HyBi protocol will be slower")
websockify_1  | WebSocket server settings:
websockify_1  |   - Listen on :80
websockify_1  |   - SSL/TLS support
websockify_1  |   - proxying from :80 to targets generated by ReadOnlyTokenFile
websockify_1  | Enter PEM pass phrase:
websockify_1  | handler exception: [Errno 22] Invalid argument
```

Currently there is no way to pass a password to `load_cert_chain`: 
https://github.com/novnc/websockify/blob/c136ea2d34146dcb75a5c5daeb7a02c6978734c5/websockify/websockifyserver.py#L580

**Comment by samhed** [comment]
Looks good!

What do you think about renaming the option to "--key-password"? I'm thinking it might help avoid some confusion.
