### ISSUE TITLE
Connection refused for local Xvfb server

### ISSUE THREAD

**Issue by anderoonies** [novnc/websockify#391]
I'm attempting to wrap `Xvfb` using the following:
```
~/code/noVNC/websockify (master *)$ ./run 5903 -- Xvfb :3
/Users/me/code/noVNC/websockify/websockify/websocket.py:30: UserWarning: no 'numpy' module, HyBi protocol will be slower
  warnings.warn("no 'numpy' module, HyBi protocol will be slower")
WebSocket server settings:
  - Listen on :5903
  - No SSL/TLS support (no cert file)
here
  - proxying from :5903 to 'Xvfb :3' (port 62569)
Starting 'Xvfb :3'
```

When I attempt to connect to the server using the native web's WebSocket (`ws = new WebSocket('ws://localhost:5903')`) the websockify server is unable to connect to the Xvfb socket:
```
127.0.0.1 - - [11/Apr/2019 14:31:04] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
127.0.0.1 - - [11/Apr/2019 14:31:04] connecting to command: 'Xvfb :3' (port 62569)
[Errno 61] Connection refused
```

**Comment by CendioOssman** [comment]
Are you sure `Xvfb` is what you want? The port 5903 suggest you are trying to get a VNC server, and Xvfb does not have that.

If it's the X11 you're after then you need to tell Xvfb to listen to port 5903. It needs to be the same port that you've specified to websockify for the magic to work.

**Comment by anderoonies** [comment]
@CendioOssman thanks for the reply! `x11vnc` was defaulting to the wrong port, resolved. thanks again
