### ISSUE TITLE
Vnc encrypt -SecurityTypes=VeNCrypt,TLSVnc

### ISSUE THREAD

**Issue by samgoud** [novnc/websockify#393]
Hi,

We had been using novnc for our project with -ssl-only option
Recently we had been asked to encrypt vnc traffic using -SecurityTypes=VeNCrypt,TLSVnc with the vnc server. We are using tigervnc 1.7 server.
When we enabled tiger vnc server with above option, novnc started to complaint "unsupported server". We are using an old version of novnc (2016)

Does the latest novnc have support for the VeNCrypt,TLSVnc encryption?
If not, are there any workarounds suggested.

Thanks

**Comment by CendioOssman** [comment]
Closing this in favour of novnc/noVNC#1230.
