### ISSUE TITLE
Enbaling Basic Web Auth

### ISSUE THREAD

**Issue by herecy** [novnc/websockify#394]
Hi, my goal is to protect NoVNC via Basic Web Auth. I tried to attach --web-auth to the NoVNC startup script, but this is not accepted.

echo "Starting webserver and WebSockets proxy on port ${PORT}"
#${HERE}/websockify --web ${WEB} ${CERT:+--cert ${CERT}} ${PORT} ${VNC_DEST} &
${WEBSOCKIFY} ${SSLONLY} --web ${WEB} ${CERT:+--cert ${CERT}} ${PORT} ${VNC_DEST} ${RECORD_ARG} --web-auth &
proxy_pid="$!"
sleep 1

Thank you in advance for any help.

**Comment by CendioOssman** [comment]
If you run the modified script it should tell you the problem:
```
run: error: You must use --auth-plugin to use --web-auth
```
So specify `--auth-plugin` (and `--auth-source`) as well and you should be fine. In your case you want the `BasicHTTPAuth` plugin.

**Comment by herecy** [comment]
Thank you for your answer.
Unfortunately it rather tells me "
Usage:
    websockify [options] [source_addr:]source_port [target_addr:target_port]
    websockify [options] [source_addr:]source_port -- WRAP_COMMAND_LINE

websockify: error: no such option: --web-auth"

I have tried to use 
${WEBSOCKIFY} ${SSLONLY}  --web ${WEB} ${CERT:+--cert ${CERT}} ${PORT} ${VNC_DEST} ${RECORD_ARG} --auth-plugin BasicHTTPAuth --auth-source target.config --web-auth &
but I get the same error that web-auth is not an option.

**Comment by CendioOssman** [comment]
Are you running an old version of websockify then? Please upgrade and it should work better.
