### ISSUE TITLE
BUG-FIX: websockifyserver.py socket.getaddrinfo port need to be casted to str

### ISSUE THREAD

**Issue by caderize** [novnc/websockify#399]
Dear WebSockify/noVNC Team

Testing noVNC/WebSockify against BaseTokenAPI I found that the connection failed
See: https://github.com/novnc/noVNC/issues/1250
 
The problem was "port" attribute of socket.getaddrinfo on websockifyserver.py (line: 461)

**From:**
`addrs = socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM,`

**To:**
`addrs = socket.getaddrinfo(host, int(port), 0, socket.SOCK_STREAM,`

**Patch** (diff -Naur websockifyserver.py.original websockifyserver.py) **:**

```
--- websockifyserver.py.original        2019-06-10 11:58:46.040671247 +0200
+++ websockifyserver.py 2019-06-10 11:57:53.632567186 +0200
@@ -458,7 +458,7 @@
             flags = flags | socket.AI_PASSIVE

         if not unix_socket:
-            addrs = socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM,
+            addrs = socket.getaddrinfo(host, int(port), 0, socket.SOCK_STREAM,
                     socket.IPPROTO_TCP, flags)
             if not addrs:
                 raise Exception("Could not resolve host '%s'" % host)
```

**Comment by CendioOssman** [comment]
This is unfortunately incorrect, as port can be a name as well (e.g. `"ssh"` will look up port 22).

What platform are you seeing your issue on? I'm not getting any problem here.

**Comment by caderize** [comment]
Dear Cendio Ossman,

you are right, 'port' is a const char*. So digging deeper I found the solution.
The problem is that using websockify with "--token-plugin=BaseTokenAPI" , port is then passed as an unicode string, but getaddrinfo() wants an ASCII string.

To reproduce the BUG:

1. Create a simple php page that echos "target_host:target_port", save it on the noVNC path
```
~$ cat /var/www/html/noVNC-1.1.0/token.php
<?php
echo "host_to_connect:5900"
?>
```

2.  Start websockify from the shell

`~$ /var/www/html/noVNC-1.1.0/utils/websockify/run --web /var/www/html/noVNC-1.1.0/ --token-plugin=BaseTokenAPI --token-source=http://myhost/noVNC-1.1.0/token.php?token=%s 8443
`

3. Open a browser to: http://myhost:8443/vnc.html?path=websockify?token=1111

See error on the console


```
WebSocket server settings:

    Listen on X.X.X.X:8443
    Web server. Web root: /var/www/html/noVNC-1.1.0
    No SSL/TLS support (no cert file)
    proxying from X.X.X.X:8443 to targets generated by BaseTokenAPI
    X.X.X.X - - [07/Jun/2019 17:02:27] X.X.X.X: Plain non-SSL (ws://) WebSocket connection
    X.X.X.X - - [07/Jun/2019 17:02:27] X.X.X.X: Path: '/websockify?token=1111'
    X.X.X.X - - [07/Jun/2019 17:02:27] connecting to: host_to_connect:5900
    X.X.X.X - - [07/Jun/2019 17:02:27] Failed to connect to host_to_connect:5900
```

**Patch** (diff -Naur websockifyserver.py.original websockifyserver.py) **:**

```
--- websockifyserver.py.original        2019-06-10 11:58:46.040671247 +0200
+++ websockifyserver.py 2019-06-10 11:57:53.632567186 +0200
@@ -458,7 +458,7 @@
             flags = flags | socket.AI_PASSIVE

         if not unix_socket:
-            addrs = socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM,
+            addrs = socket.getaddrinfo(str(host), str(port), 0, socket.SOCK_STREAM,
                     socket.IPPROTO_TCP, flags)
             if not addrs:
                 raise Exception("Could not resolve host '%s'" % host)
```

N.B.: I have also converted 'host' to "str"


```

**Comment by CendioOssman** [comment]
Ah, I see. However I think we can push this requirement to the plugins. I.e. they should return sane things. So fix `BaseTokenAPI` instead. And make sure it has some error handling. A dumb cast will just crash if we have non-ASCII data.

Also note that it's perfectly legal for `host` to be unicode. Host names aren't restricted to just ASCII.

**Comment by caderize** [comment]
Hostname, from RFC 1123 (See: https://en.wikipedia.org/wiki/Hostname), has a maximum of 253 ASCII characters. You can store Unicode chars using: Punycode, that is a representation of Unicode with the limited ASCII character subset used for Internet host names.

Fixing the `BaseTokenApi` is fine, but is also good and needed to cast host and port to ASCII-string on `socket.getaddrinfo()`

**Comment by caderize** [comment]
A simple patch to `token_plugins.py` that force result to be ASCII string, so a dumb cast in `websockifyserver.py` will not crash.

**Patch:** (diff -Naur token_plugins.py.original token_plugins.py):
```
--- token_plugins.py.original   2019-06-18 11:16:29.246510580 +0200
+++ token_plugins.py    2019-06-18 11:16:17.302493313 +0200
@@ -68,7 +68,7 @@
     # in this file can be used w/o unecessary dependencies

     def process_result(self, resp):
-        return resp.text.split(':')
+        return resp.text.encode('ascii','ignore').split(':')

     def lookup(self, token):
         import requests

```

**Comment by CendioOssman** [comment]
I don't think we should force people to store tokens in punycode as that format is not very readable. And `socket.getaddrinfo()` gladly accepts unicode and converts it to punycode for us. E.g. this works:

```python
import socket
socket.getaddrinfo(u'försäkringskassan.se', 'https', 0, socket.SOCK_STREAM, socket.IPPROTO_TCP, 0)
```

So let's be user friendly and accept normal unicode for the host. :)

**Comment by caderize** [comment]
Sorry for the late answer...

This patch keeps `host` as unicode and convert `port` to ASCII string. As a bonus it also fix a typo.

**Patch:** (diff -Naur token_plugins.py.original token_plugins.py):
```
--- token_plugins.py.original   2019-06-18 11:16:29.246510580 +0200
+++ token_plugins.py    2019-07-02 12:26:09.697672783 +0200
@@ -65,10 +65,12 @@
     # should go

     # we import things on demand so that other plugins
-    # in this file can be used w/o unecessary dependencies
+    # in this file can be used w/o unnecessary dependencies

     def process_result(self, resp):
-        return resp.text.split(':')
+        host, port = resp.text.split(':')
+        port = port.encode('ascii','ignore')
+        return [ host, port ]

     def lookup(self, token):
         import requests
```

Hope you can add this little patch to the project

**Comment by CendioOssman** [comment]
Committed as b46fab5608c9199f5336ed3a851e59b084dde842. Thanks for you patch. :)
