### ISSUE TITLE
Can't install bluetooth-dev on Raspbian Stretch - no install candidate

### ISSUE THREAD

**Issue by lrhorer** [novnc/websockify#401]
There is no install candidate for bluetooth-dev on Rasbpian Stretch with Python 2.7.13 and 3..5.3, however, the docs only talk about Python versions older than those.  Does that mean bluetooth-dev is not needed with newer version of Python?  The README.md is not clear on this.  A similar issue may exist for ssl-1.15.tar.gz.  When I attempt to wget this file per the instructions in the README.md, I get a 403 error complaining I need SSL in order to fetch the file.

**Comment by CendioOssman** [comment]
The ssl module should be included with your Python, so you should not have to build it yourself with current systems. Have you tried starting websockify?

**Comment by lrhorer** [comment]
Yes, and although it does not give an error, it also does not seem to work properly.  When I connect, it doesn't respond.

**Comment by CendioOssman** [comment]
What client are you using to connect? websockify isn't terribly chatty in its logs, so you might not see much there.

**Comment by lrhorer** [comment]
I'm sorry, I don't recall.  I finally just gave up and used a different solution.
