### ISSUE TITLE
Can I run it on windows for multiple connection

### ISSUE THREAD

**Issue by ShaneHuHu** [novnc/websockify#408]
When I run it with no options on windows, I got this error:

> handler exception: Can't pickle <type 'thread.lock'>: it's not found as thread.l
> ock
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "D:\Python27\lib\multiprocessing\forking.py", line 380, in main
>     prepare(preparation_data)
>   File "D:\Python27\lib\multiprocessing\forking.py", line 488, in prepare
>     assert main_name not in sys.modules, main_name
> AssertionError: __main__

It happens when a connection connected.
So I run it by --run-once option, it works but server exist after connection closed. 
May I ask how could I avoid this exception so that I could use it on my windows server to host our application on the web? Many thanks for the help, sir!

**Comment by samhed** [comment]
Windows is not supported by websockify. There has been some people who managed to get things working somewhat I believe, but you'd be largely on your own. See this issue #309 and others linked from it

**Comment by ShaneHuHu** [comment]
I got it, many thanks sir.

**Comment by CendioOssman** [comment]
We actually managed to get Windows working again as of #388.

@ShaneHuHu, what version of websockify are you using?

**Comment by samhed** [comment]
No response.
