### ISSUE TITLE
How to change the path of /websockify request?

### ISSUE THREAD

**Issue by parthmishra** [novnc/websockify#409]
I'm not sure if this is the correct place to ask, but let's say I have my VNC server hosted at `example.com/myserver/`. Currently, the websockify makes a ws connection at `example.com/websockify` but I want it instead to make that connection at `example.com/myserver/websockify`. Is there any way to do this? Do I have to make changes to the run command and/or my NGINX configuration?

**Comment by samhed** [comment]
Could you share your nginx config and the command you use to start websockify?

**Comment by samhed** [comment]
No response
