### ISSUE TITLE
Use zstack novnc hava a  error problem?

### ISSUE THREAD

**Issue by liujunwe** [novnc/websockify#410]
when i opening novnc in brower:console error is :

websock.js:285 WebSocket connection to 'ws://localhost:17523/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I find this row code in websoc.js . I cant understand ws://localhost:17523/ .this line of code do ?

I`m wating for reply ,thanks

**Comment by CendioOssman** [comment]
I'm afraid this has nothing to do with websockify but rather the Javascript you are using. Since you've already commented on novnc/noVNC#685 please see my reply there.

**Comment by liujunwe** [comment]
> I'm afraid this has nothing to do with websockify but rather the Javascript you are using. Since you've already commented on [novnc/noVNC#685](https://github.com/novnc/noVNC/issues/685) please see my reply there.

ok，thank you
