### ISSUE TITLE
Modify websockify to support reverse connections

### ISSUE THREAD

**Issue by Master0711** [novnc/websockify#412]
Is it possible to support noVNC reverse connection by modifying websockify?Run this command on the client（winvnc.exe -connect proxyIp:proxyPort -run）.Websockify receives the connection request and establishes a connection，in order to support the NAT network environment.

**Comment by CendioOssman** [comment]
In theory I suppose. But I don't think anyone is working on it. You may also need some modification in you VNC client, depending on what timeouts it might have.

But I'm afraid it's nothing someone is looking at, so you'll have to experiment yourself.
