### ISSUE TITLE
websockify support more  spicehtml5 client error?

### ISSUE THREAD

**Issue by liujunwe** [novnc/websockify#415]
I want to use websockify to proxy multiple spicehtml5 backends at the same time, using Token mechanism (like novnc's proxy mechanism), but spice html5 connection error, "**unknown protocol**", how can I modify websockify to support it to proxy multiple spicehtml5 clients?

============
_Looking forward to your advice_

**Comment by CendioOssman** [comment]
I'm afraid I don't know enough about spicehtml5 to determine what you are trying to do.

Could you please describe in detail what you've done?

**Comment by samhed** [comment]
No response.
