### ISSUE TITLE
[Help] Websockify connection over apache2 reverse proxy

### ISSUE THREAD

**Issue by jupiterbjy** [novnc/websockify#418]
I've searched google for a last full month, yet couldn't figure out how to connect to websockify over WAN.

Websockify does run flawlessly in localhost when setting websockify location as '/utils/websockify/run', but since I'm stuck in army where only 80 port is available - I need reverse proxy desperately. Since Owncloud is also running over port 80, there is no other option.

Below is current setting of apache2 reverse proxy + launch option for noVNC. Upon pressing connect, nothing appears on websockify at all, probably fault on reverse proxy.

![캡처](https://user-images.githubusercontent.com/26041217/69897028-80c40a00-1389-11ea-9db7-a87f7a14093c.PNG)

noVNC is located at /var/www/noVNC, and is direct clone of github repository. Not sure here is right place to ask, but this is my last resort - Any recommendations are appreciated.

**Comment by jupiterbjy** [comment]
Figured out when trying this via nginx, seems like it was missing http header that was causing issue.

**Comment by samhed** [comment]
Good to hear! Apologies for giving you an answer - must've gotten lost between the chairs this one.
