### ISSUE TITLE
Websockify not working as intended.

### ISSUE THREAD

**Issue by duysqubix** [novnc/websockify#419]
I am scouting to to look for a websocket to TCP proxy, without needing to reinvent in the wheel. I stumbled upon this great repo, because it could be exactly what I am looking for. However, even a simple set up doesn't work, not sure what I am doing wrong. I am using Ubuntu 18.04 LTS.

I have three terminal windows up. The 1st i used websockify to proxy to a TCP address

Window 1 - Setup Proxy
`127.0.0.1:8080 -> 127.0.0.1:8001`

Window 2 - Connect to Websocket via client using Websocat
`websocat ws://127.0.0.1:8080` // accepts connection

Window 3 - Create a fast TCP server using nc
`nc -l 8001`

When typing on Window 2 I don't see the end result being displayed on Window 3 and vice versa..?

Link to [screenshot](https://i.imgur.com/Nrp4Vcj.png)

**Comment by CendioOssman** [comment]
It will not work if you do things in that order. The "real" server (i.e. `nc`) must be running before the WebSocket connection is made or there is nothing for websockify to connect to.

Please try starting `nc` first and you should be fine.
