### ISSUE TITLE
websockify doesn't work on RHEL 6

### ISSUE THREAD

**Issue by samhed** [novnc/websockify#420]
Trying to start websockify on RHEL 6 gives:

    Starting webserver and WebSockets proxy on port 6080
    /usr/bin/python: websockify is a package and cannot be directly executed
    Failed to start WebSockets proxy

RHEL 6 has Python 2.6, this issue seems to have been fixed in python 2.7:

https://bugs.python.org/issue2751

**Comment by CendioOssman** [comment]
We don't care about such old platforms anymore.
