### ISSUE TITLE
TCP stream segmentation into messages?

### ISSUE THREAD

**Issue by alexchandel** [novnc/websockify#425]
What is websockify's policy for segmenting the TCP response stream into WebSocket messages?  Could you explicitly document this?

A nice additional feature would be to accept a simple decoding codec that frames the stream into predetermined message boundaries, [like this interface](https://docs.rs/tokio-util/0.2.0/tokio_util/codec/trait.Decoder.html).

**Comment by CendioOssman** [comment]
It's just bytes (same as TCP) as websockify is just a low level bridge. We don't have any plans to make it more specific than that.

**Comment by alexchandel** [comment]
@CendioOssman Except it can't be.  WebSocket messages have defined boundaries.  How does websockify decide where to segment the TCP stream into WebSocket messages?

**Comment by CendioOssman** [comment]
It's completely arbitrary, much like TCP. It's up to the receiving end to piece together the higher level protocol.
