### ISSUE TITLE
Possible to serve files alongside Express?

### ISSUE THREAD

**Issue by SterlingButters** [novnc/websockify#426]
I am already using Express to serve a bunch of files and listen on a certain port but in order to integrate noVNC into my application, the use of Websockify appears mandatory. Is there any way to use the Websockify proxy and Express simultaneously? 

How does `Websockify` serve files? http(s)?

What would this look like? 

As I understand it (for noVNC) `Websockify` just grabs the `rfb` object/data from port `5900` and then bridges that to the port on which the files are being served. I don't understand how the `rfb` object is actually received by `vnc_lite.html` (in my case). I have tried to use `Websockify` alongside `Express` just to see what would happen and no surprise that it claims the port is busy. 

I've also considered just letting `Websockify` serve my files but I am hoping to get some sort of confirmation that this will behave similarly to `Express` before I go and change a bunch of stuff.

**Comment by samhed** [comment]
Websockifty isn't mandatory for noVNC. There are VNC servers with builtin websocket->TCP proxies. 
You also don't have to use websockify as a web server, you could only use the proxy part.

**Comment by SterlingButters** [comment]
@samhed Thank you for confirming - I forgot to come back and close this after I actually got it working
