### ISSUE TITLE
error: compiling 'run' failed

### ISSUE THREAD

**Issue by nest-center** [novnc/websockify#431]
```sh
C:\Users\xxxx\Downloads\websockify-master> Python setup.py py2exe --includes numpy
C:\Portable Python 2.7.6.1\App\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running py2exe
running build_py
running egg_info
writing requirements to websockify.egg-info\requires.txt
writing websockify.egg-info\PKG-INFO
writing top-level names to websockify.egg-info\top_level.txt
writing dependency_links to websockify.egg-info\dependency_links.txt
writing entry points to websockify.egg-info\entry_points.txt
reading manifest file 'websockify.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'LICENSE.txt'
warning: no directories found matching 'include'
writing manifest file 'websockify.egg-info\SOURCES.txt'
*** searching for required modules ***
error: compiling 'run' failed
    SyntaxError: invalid syntax (run, line 3)
```

**Comment by nest-center** [comment]
setup.py

from setuptools import setup, find_packages
# add (line 2):
import py2exe

version = '0.9.0'
name = 'websockify'
long_description = open("README.md").read() + "\n" + \
    open("CHANGES.txt").read() + "\n"

setup(name=name,
      # add (line 10):
      console=['run'],
      version=version,
      description="Websockify.",
      long_description=long_description,
      long_description_content_type="text/markdown",
      classifiers=[
          "Programming Language :: Python",
          "Programming Language :: Python :: 2",
          "Programming Language :: Python :: 2.6",
          "Programming Language :: Python :: 2.7",
          "Programming Language :: Python :: 3",
          "Programming Language :: Python :: 3.3",
          "Programming Language :: Python :: 3.4"
        ],
      keywords='noVNC websockify',
      license='LGPLv3',
      url="https://github.com/novnc/websockify",
      author="Joel Martin",
      author_email="github@martintribe.org",

      packages=['websockify'],
      include_package_data=True,
      install_requires=['numpy'],
      zip_safe=False,
      entry_points={
        'console_scripts': [
            'websockify = websockify.websocketproxy:websockify_init',
        ]
      },
    )

**Comment by samhed** [comment]
I know you can use websockify-js on Windows:

https://github.com/novnc/websockify-js/wiki/Running-websockify-js-on-Windows

Not sure about this Python version.. I seem to recall we got this working as well somehow, didn't we @CendioOssman?

**Comment by CendioOssman** [comment]
websockify works on Windows these days as well.

The problem here is that @nest-center is trying to compile a shell script (`run`) as a Python script. Which obviously fails. I'm afraid you'll have to tweak your setup somehow. Unfortunately I can't really tell you how as py2exe is not something we target or support.
