### ISSUE TITLE
websockify behind a reverse proxy

### ISSUE THREAD

**Issue by DerT94** [novnc/websockify#434]
Hi,

I would like to use noVNC with websockify behind an apache reverse proxy.
noVNC and websockify are running on "server1" on port 6081 an work.
I can connect to the server via "http://server1:6081".

If I try the connection through my reverse proxy I get some errors in the console.
![image](https://user-images.githubusercontent.com/58786605/86112595-7bb66d00-bac8-11ea-9228-c5c609dd41d9.png)

I tried the following config. (My domains were replaced with example.com or example.loc)

```
<VirtualHost *:80>
 ServerName remote.example.com
 ProxyPreserveHost On
 ProxyPass /.well-known !
 ProxyPass / http://dialin.example.loc:6081/
 ProxyPassReverse / http://dialin.example.loc:6081/
 ProxyPass / ws://dialin.example.loc:6081/ retry=3
 ProxyPassReverse / ws://dialin.example.loc:6081/
</VirtualHost>
```

Apache Version: 2.4.41

Enabled Apache Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_ajp_module (shared)
 proxy_balancer_module (shared)
 proxy_connect_module (shared)
 proxy_html_module (shared)
 proxy_http_module (shared)
 proxy_wstunnel_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 xml2enc_module (shared)

**Comment by catborise** [comment]
did you check webvirtcloud/settings.py file?

may be you should change this 
```
# Websock public port - 80 or 443 if reverse-proxy, else 6080
WS_PUBLIC_PORT = 6080
```

**Comment by DerT94** [comment]
where can I find the file?
I have installed noVNC and Websockify from the package lists.

`apt -y install novnc websockify python-numpy`

**Comment by catborise** [comment]
sorry my mistake. it is unrelated with your problem.

**Comment by CendioOssman** [comment]
I'm afraid this is outside our expertise. You should check with the Apache people (or their docs) on how to proxy WebSocket connections. You could also try asking on the noVNC mailing list if someone else has gotten this setup running.

**Comment by thangisme** [comment]
Have you found out any solution to this?

**Comment by DerT94** [comment]
Yes

```
<VirtualHost *:80>
   ServerName remote.example.de
   RewriteEngine on
   RewriteCond %{HTTP:Upgrade} websocket [NC]
   RewriteCond %{HTTP:Connection} upgrade [NC]
   RewriteRule .* "ws://dialin.example.loc:6081%{REQUEST_URI}" [P]
   ProxyPass / http://dialin.example.loc:6081/
   ProxyPassReverse / http://dialin.example.loc:6081/
  RewriteCond %{SERVER_NAME} =remote.example.de
  RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>


```
