### ISSUE TITLE
An error is reported when disconnecting and disconnect event was not triggered.

### ISSUE THREAD

**Issue by ApsarasX** [novnc/websockify#436]
**Describe the bug**
An error is reported when disconnecting. And disconnect event was not triggered.

**To Reproduce**
I followed ‘Quick Start’ of README.md

**Expected behavior**
No error was throwed and disconnect event could be triggered normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/24390069/87461696-5a658d00-c641-11ea-92f6-83ef02291ec8.png)
![image](https://user-images.githubusercontent.com/24390069/87461722-60f40480-c641-11ea-8d8a-20e22ee94cc6.png)

**Client (please complete the following information):**
 - OS: macOS 10.15
 - Browser: Chrome
 - Browser version: 83

**Server (please complete the following information):**
 - noVNC version: 1.1.0 or 1.2.0
 - VNC server: X11VNC
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
What does the log on websockify say when this happens?

**Comment by ApsarasX** [comment]
> What does the log on websockify say when this happens?
![截屏2020-07-17 08 56 25](https://user-images.githubusercontent.com/24390069/87736779-a106e300-c80b-11ea-8dc7-8e48ea614a67.png)

Logs are only printed when connected, but not when disconnected.

**Comment by CendioOssman** [comment]
That's unfortunate.

Do you see the same message with Safari?

And can you get some more details from the browser about that close? Can you see what the code is that the browser is upset about.

**Comment by ApsarasX** [comment]
Safari is the same.

In addition to the screenshot above, I found this error in the network tab of the browser developer tool
![image](https://user-images.githubusercontent.com/24390069/88245743-e5422980-ccca-11ea-823c-32aa0b16a085.png)

**Comment by CendioOssman** [comment]
Well that wasn't a terribly helpful message from the browser. :/

Do you think you could test Firefox? It uses a completely different engine compared to Chrome and Safari and might show us more details.

**Comment by CendioOssman** [comment]
No response. Closing.
