### ISSUE TITLE
vnc playback for recordings doesn't seems to be working

### ISSUE THREAD

**Issue by sonisrje** [novnc/websockify#442]
I created the recordings directory and move one of the recordings to it. Thereafter I am trying to access the URL as follows: https://macc02vk4lrg8wn:6090/tests/vnc_playback.html?data=record.2

But still it gives the below error:

Loading record.2...
Error loading recording: ReferenceError: vncFrameData is not defined

Can you please help me with this? I am also attaching the screenshot herewith.
<img width="737" alt="Screenshot 2020-08-27 at 3 17 21 PM" src="https://user-images.githubusercontent.com/44198033/91480875-3395aa00-e8c1-11ea-9a0c-caa9cdb53ad1.png">

This is how I am recording the session:

./utils/launch.sh --vnc ***.***.***.**:5900 --ssl-only --listen 6090 --record session

**Comment by samhed** [comment]
This was a bug in noVNC - now fixed.
