### ISSUE TITLE
websockify stops working with latest Chrome/Firefox and the Microsoft Edge

### ISSUE THREAD

**Issue by allenzhao64** [novnc/websockify#443]
Starting from May, the websockify stops working on Chrome and Firefox, and recently with Windows update installed the new Edge, the web access all stuck at the grey screen.

Is there any update or fix to address the issue?

![image](https://user-images.githubusercontent.com/27832525/92155459-0b400b00-eded-11ea-91c7-1fd5b5f1df16.png)

**Comment by allenzhao64** [comment]
I have tested the latest codes for both noVNC and Websokify.

**Comment by allenzhao64** [comment]
the legacy Microsoft Edge still functions as expected.

**Comment by samhed** [comment]
Works for me with the latest versions of Chrome, Firefox and the new Edge as well.

For starters, how does the output from websockify look? Are you getting any errors?
What VNC server are you using?

**Comment by CendioOssman** [comment]
Please fill out the bug form so we get a better picture of the environment you have.

**Comment by allenzhao64** [comment]
Where is the bug form?

Here is a real example: https://wave.gtisoft.com:20004/ you can see the issue.

The server side: 
OS: Windows 10 Pro
Python: 3.8.2 
VNC server: tightVNC (tightvnc-2.8.27-gpl-setup-64bit)

This is the command I launch the noNVC (you can tell all the installation path from it):
C:\noVNC\websockify>python websockify 5901 127.0.0.1:5900 --web c:\noVNC\noVNC-master --cert=C:\noVNC\websockify\self.pem

The self.pem is created by OpenSSL `C:\noVNC\websockify>openssl req -new -x509 -days 365 -nodes -out self.pem -keyout self.pem`

I have tried to use Godaddy SSL, but it is not working. the self.pem has been working perfectly until recent Chrome update. 

I have not tested noVNC without self.pem (right now the machine is in use)

**Comment by allenzhao64** [comment]
> Works for me with the latest versions of Chrome, Firefox and the new Edge as well.
> 
> For starters, how does the output from websockify look? Are you getting any errors?
> What VNC server are you using?

From the console output, it seems to be ok, no error.

**Comment by CendioOssman** [comment]
Sorry, your screen shot showed a noVNC issue so I figured we were in the noVNC repo. But I see we are in the websockify one.

Could you please share a screenshot of the web console when loading the page? I'm not aware of any scenario where it fails to load without logging something.

Please also check the network tab for any errors.

**Comment by allenzhao64** [comment]
> Sorry, your screen shot showed a noVNC issue so I figured we were in the noVNC repo. But I see we are in the websockify one.
> 
> Could you please share a screenshot of the web console when loading the page? I'm not aware of any scenario where it fails to load without logging something.
> 
> Please also check the network tab for any errors.

You can just visit https://wave.gtisoft.com:20004/  to see the issue there. Is there any other web console that I can check?

From command line:
C:\noVNC\websockify>python websockify 6080 127.0.0.1:5900 --web c:\noVNC\noVNC-master --cert=C:\noVNC\websockify\self.pem
WARNING: no 'resource' module, daemonizing is disabled
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: c:\noVNC\noVNC-master
  - SSL/TLS support
  - proxying from :6080 to 127.0.0.1:5900
WARNING: no 'resource' module, daemonizing is disabled
WARNING: no 'resource' module, daemonizing is disabled

It seems every external web access session will add another line of that "WARNING:" line . That is all it shows, with regardless if it is bad Chrome session or a good legacy Edge session.

**Comment by CendioOssman** [comment]
> You can just visit https://wave.gtisoft.com:20004/ to see the issue there. Is there any other web console that I can check?

It fails to load for me as well, and in the console I get a whole bunch of errors:

```
The script from “https://wave.gtisoft.com:20004/vendor/promise.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. wave.gtisoft.com:20004
The script from “https://wave.gtisoft.com:20004/app/error-handler.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. wave.gtisoft.com:20004
Loading module from “https://wave.gtisoft.com:20004/app/ui.js” was blocked because of a disallowed MIME type (“text/plain”). wave.gtisoft.com:20004
Loading failed for the module with source “https://wave.gtisoft.com:20004/app/ui.js”. wave.gtisoft.com:20004:66:1
```

The issue is that your web server is not correctly set up and is serving files with the wrong MIME type. In this case it is websockify, so the issue is that your Python is broken in some way so that the MIME module isn't working properly. On Linux this is usually because the MIME database isn't installed, but I'm afraid I have no idea what the issue might be on Windows.

I'm afraid I'll have to point you to the Python people and see if they can help you figure out why Python's MIME module isn't working. There is unfortunately nothing more we can do in our end.

**Comment by allenzhao64** [comment]
On linux, I guess you use pip, which module are you installing for this MIME db? let me know.

**Comment by CendioOssman** [comment]
Unfortunately it is a system component, not a Python package, so it isn't available via pip. It's called "shared-mime-info" on Linux systems, but I have no idea what Python uses on Windows.

**Comment by Everydaytobecontinued** [comment]
这个问题我已经解决了。我使用的是noVNC 1.3.0 和websockify 0.10.0版本，python使用的是3.10.4。
我并没有学习过python。不过通过我调试python代码发现问题出现在哪里了。
正如作者所说，他们是通过Http请求的本地文件路径扩展名来确定返回的文件请求头类型 。
通过调试查看http.server文件。"这个文件在C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\http"
调试python文件的send_head()=>guess_type(path)发现通过posixpath.splitext方法根据路径获取的.js后缀名字的文件头类型。返回的content-type类型都是text/plain.但是我们知道novnc 1.3.0版本引用的js都是通过type="module" 模组的方式导入的。
所以浏览器会警告你 不接受 js导入标记为 type="module" 却通过content-type:text/plain的当时返回。
extensions_map 属性添加默认头类型
'.js':'application/javascript'
这个问题就解决了。
![微信截图_20220404181132](https://user-images.githubusercontent.com/26613332/161523271-75791a73-b369-46ae-8af2-c8a2f6205724.png)
