### ISSUE TITLE
How to deal with the plaintext of novnc private key and when will it support encryption

### ISSUE THREAD

**Issue by 3zhaochen** [novnc/websockify#445]
How to deal with the plaintext of novnc private key and when will it support encryption

**Comment by CendioOssman** [comment]
Probably never, I'm afraid. websockify is a toy example server to make it easier to test things. It is not designed to be secure, scalable or many other things you want from a production system.

**Comment by 3zhaochen** [comment]
After the websockify/run --key "$CERT_KEY" --key "$CERT_KEY" ----key-password "$keyPassword" --ssl-version tlsv1_2 --ssl-ciphers ECDHE-RSA-AES256-GCM-SHA384 -D "${hostName}":"${sPort}" "${vncUrl} connection is successful, run the ps -ef|grep port number command to check the process. The private key password has security issues. How to solve this problem?

**Comment by 3zhaochen** [comment]
> Probably never, I'm afraid. websockify is a toy example server to make it easier to test things. It is not designed to be secure, scalable or many other things you want from a production system.

After the websockify/run --key "$CERT_KEY" --key "$CERT_KEY" ----key-password "$keyPassword" --ssl-version tlsv1_2 --ssl-ciphers ECDHE-RSA-AES256-GCM-SHA384 -D "${hostName}":"${sPort}" "${vncUrl} connection is successful, run the ps -ef|grep port number command to check the process. The private key password has security issues. How to solve this problem?
