### ISSUE TITLE
TLS version tlsv1_3 unsupported. Falling back to tlsv1_2

### ISSUE THREAD

**Issue by duanwujie** [novnc/websockify#447]
/usr/local/bin/websockify --cert /etc/pki/vdsm/libvirt-spice/server-cert.pem --key=/etc/pki/vdsm/libvirt-spice/server-key.pem  --ssl-version=tlsv1_3 5959 172.30.24.123:5911

Run the command get the following error, how to enable tlsv1_3 ?
	
```
TLS version tlsv1_3 unsupported. Falling back to tlsv1_2
WebSocket server settings:
  - Listen on :5959
  - SSL/TLS support
  - proxying from :5959 to 172.30.24.123:5911

```

**Comment by CendioOssman** [comment]
You'll need to run websockify in Python 3 to get that support. So please modify your `/usr/local/bin/websockify` and make sure it uses Python 3 and not Python 2.
