### ISSUE TITLE
Can not connect with websockify daemon

### ISSUE THREAD

**Issue by duanwujie** [novnc/websockify#448]
We can connect to websockify without the -D option, but it fails with the -D option

websockify --cert /etc/pki/vdsm/libvirt-spice/server-cert.pem --key /etc/pki/vdsm/libvirt-spice/server-key.pem --cafile /etc/pki/vdsm/libvirt-spice/ca-cert.pem --ssl-target 9900 172.30.24.201:5900 -D --log-file=test.txt

The log bellow:

```
WebSocket server settings:
  - Listen on :9900
  - SSL/TLS support
  - Backgrounding (daemon)
  - proxying from :9900 to 172.30.24.201:5900 (using SSL)
172.30.24.254 - - [25/Sep/2020 13:38:28] 172.30.24.254: Plain non-SSL (ws://) WebSocket connection
172.30.24.254 - - [25/Sep/2020 13:38:28] connecting to: 172.30.24.201:5900 (using SSL)
handler exception zlfan1: [Errno 95] Operation not supported
```

**Comment by CendioOssman** [comment]
Hmm... Odd. Could you enable `--verbose` and it should tell us more about the crash?

**Comment by CendioOssman** [comment]
No response. Closing.
