### ISSUE TITLE
Avoid number at the begining of json output

### ISSUE THREAD

**Issue by nikogrnr** [novnc/websockify#454]
Hello,

I don't understand why there is a leading number at the begining of the json output of websockify and how ti avoid it.

Example :
{107503{{"agent": {"id": "a31fc", "type": "filebeat", "version": "7.9.2'}}}}

My app can't understand this number and need only this :
{"agent": {"id": "a31fc", "type": "filebeat", "version": "7.9.2'}}

Of perharps I miss something, thanks

**Comment by CendioOssman** [comment]
Where is this JSON from? It's not something I recognize.

**Comment by nikogrnr** [comment]
I got it from the output file of the --record= option

**Comment by CendioOssman** [comment]
It doesn't really match that either. Can you share the entire file with us?

**Comment by nikogrnr** [comment]
Here the content of the file :

var VNC_frame_data = [
'{59393{{"agent":{"type":"filebeat","version":"7.9.2","hostname":"toto.ici.la","id":"a31fc987-cd28-43b1-85eb-bb9548c86ca8","ephemeral_id":"9151cd9f-6c3d-40fe-829d-46742b7002ea","name":"toto.ici.la"},"write_steeven":"ko","host":{"name":"toto.ici.la"},"textmsg":"\\" ### ACTIVATION DE LA PROCEDURE : FEX_Fenetre_S sur labas reprise a l\'etape : 1 ### \\"  ","@timestamp":"2020-10-22T12:43:48.000Z","send_transverse":"ko","facil":"agenda","logstash_timestamp":"2020-10-22T12:43:49.726Z","simulatedDate":"N/A","parsed_logdate":"2020-10-22T12:43:48.000Z","message":"2020-10-22_12:43:48 toto.ici.la user_number_60000 RE1 NAEPENCHTPGT  NAptsrep CAE 1 C 012  \\" ### ACTIVATION DE LA PROCEDURE : FEX_Fenetre_S sur datalocal reprise a l\'etape : 1 ### \\"  ","user":["N/A","user_number_60000"],"logstash_date":"2020-10-22T12:43:49.726Z","@version":"1","hostname":"toto.ici.la","input":{"type":"log"},"logdate":"2020-10-22_12:43:48","num_message":"1","write_file_operations":"ok","write_file":"ok","write_websocket_operations":"ok","ruby_diff":1,"level_agenda":"C","fullhostname":"toto.ici.la","model":"S111","loghost":"toto.ici.la","ecs":{"version":"1.5.0"},"log":{"file":{"path":"/data/S111/AGENDA/AGENDA/JDB/logbook"},"offset":188754},"type":"agenda","write_websocket":"ok","sat_agenda":"S11","tags":["agenda","beats_input_codec_plain_applied"],"second_level_agenda":"AE","source":"/data/S111/AGENDA/AGENDA/JDB/logbook","level":"info"}',
'EOF'];

**Comment by CendioOssman** [comment]
Ah. So your data you are sending over the WebSocket is also JSON. That's what got me confused.

Note that the strings in the recording are not JSON. They just happen to use `{` and `}` as delimiters. Each entry in the array is a WebSocket frame. And it uses `{` and `}` depending on the direction of the frame. The number between the delimiters is a timestamp in milliseconds. This is part of the format so your parser will need to handle it and separate it from the data.
