### ISSUE TITLE
Stale client processes remain on unclean disconnect

### ISSUE THREAD

**Issue by jcpunk** [novnc/websockify#456]
I've got a number of users who now VPN into the site, fire up their noVNC sessions, and then terminate VPN when they are done.

The do not cleanly click 'Disconnect' in the window to terminate the noVNC/WebSocket.  They just close the VPN, which itself drops the routes and doesn't send the relevant 'close' signals.

There appears to be some heartbeat code within websockify, but that doesn't seem to be killing off our stale client sessions when activated.

**Comment by CendioOssman** [comment]
What does the process tree look like in such cases?

And what setting have you used for heartbeat?

**Comment by jcpunk** [comment]
Good news, looks like I had my apache proxy set wrongly.

I needed to add `disablereuse=On` to my ProxyPass options.  The apache daemon was keeping the connection alive for if the client came back.
