### ISSUE TITLE
Issue with launch.sh

### ISSUE THREAD

**Issue by hamidp555** [novnc/websockify#461]
running utils/launch.sh returns the following error: 

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "websockify/__init__.py", line 1, in <module>
    from websockify.websocket import *
  File "websockify/websocket.py", line 25, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse`

**Comment by DarioIrribarra** [comment]
Hi! This also happened to me yesterday when I was using a virtual Raspbian OS. The thing is that there the python by default is 2 and websockify uses python 3. So the way around this for me was to edit the websockify/run file and change the "python" word to "python3". That fixes this issue. I think it would be great if the run file came with that by default. 

I hope it helps

**Comment by CendioOssman** [comment]
Ah. That is probably reasonable, yes. Fixed in 108f993eb387d10fbc6ebb632f4fb92c8c44a15b.

**Comment by hamidp555** [comment]
thanks @DarioIrribarra @CendioOssman
