### ISSUE TITLE
help me to compile python for Windows

### ISSUE THREAD

**Issue by userremyx** [novnc/websockify#469]
*** searching for required modules ***
error: compiling 'run' failed
    SyntaxError: invalid syntax (run, line 3)

![image](https://user-images.githubusercontent.com/77745209/105210467-75014d00-5b21-11eb-8aad-b94ba8e90bbc.png)

**Comment by lvbirui** [comment]
the wiki said :Compiling Websockify as Windows Executable (not working nowadays)
I also finding the way to run websokify in windows.

**Comment by CendioOssman** [comment]
`run` is a shell script, so it won't be able to parse that. But I'm not sure why it is even trying. Exactly which commit do you have in that build?

**Comment by patrakov** [comment]
Please don't even try to compile. If you are trying to run websockify as a service, see my pull request: https://github.com/novnc/websockify/pull/474
