### ISSUE TITLE
 handler exception: 'array.array' object has no attribute 'fromstring'

### ISSUE THREAD

**Issue by duportail** [novnc/websockify#473]
It looks like Python 3.9 removed fromstring()
how to solve novnc?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Browser version: [e.g. 22]

**Server (please complete the following information):**
 - noVNC version: [e.g. 1.0.0 or git commit id]
 - VNC server: [e.g. QEMU, TigerVNC]
 - WebSocket proxy: [e.g. websockify]

**Additional context**

**Comment by CendioOssman** [comment]
Indeed. This was already fixed in 33710b397230e239a202c650ceaa8148a1a45c01. So an update will solve this.
