### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by TechComSpot** [novnc/websockify#477]
**Describe the bug**
NoVNC IS NOT OPENNING IN A BROWSER 

**Expected behavior**
NoVNC SHOULD OPENED IN A BROWSER 

1. I cloned a repo with git into Termux
2. Executed ./utils/launch.sh --vnc localhost:5901
3. Copied link: http://025d001e150b:6080/vnc.html?host=025d001e150b&port=6080
4. Pasted it in browser
5. Got an error

Actual results:
NoVNC IS NOT OPENNING IN A BROWSER

**Comment by CendioOssman** [comment]
That looks like a container hostname, and websockify cannot really know if that is reachable or not. You'll have to configure your container to make sure to export port 6080, and use whatever external hostname you have for the machine (I'm guessing 127.0.0.1 in your use case).

How to do this is unfortunately out of scope for this project so you'll have to check with the project that has set up that environment.
