### ISSUE TITLE
exit websockify when handler exeption is raised

### ISSUE THREAD

**Issue by pdemilly** [novnc/websockify#480]
I need to have websockify exit when the connection with the client is broken or after a delay of not receiving an heartbeat would be ideal. Is there a flag I could use for that.

I tried to raise self.Terminate() or self.exit() in the except Exception: block where this handler exception is happening but I am getting an error

Durrng handling of the above exception, another exception ...

**Comment by samhed** [comment]
Perhaps the `--run-once` flag works the way you expect?

**Comment by CendioOssman** [comment]
No response. Closing.
