### ISSUE TITLE
Failed when connecting: Connection closed (code: 1011, reason: Failed to connect to downstream server)

### ISSUE THREAD

**Issue by ximury** [novnc/websockify#482]
What is the reason for such errors in the process of using novnc connection?

**Comment by CendioOssman** [comment]
That means it could not connect to the server you specified to websockify. What does the log output say?

**Comment by ximury** [comment]
Thanks,I've solved this problem with an upgraded version

**Comment by CendioOssman** [comment]
Glad to hear it. Closing this issue.
