### ISSUE TITLE
can i pass my rtsp stream to websocket using this

### ISSUE THREAD

**Issue by Nidheeshv0312** [novnc/websockify#483]

**Comment by CendioOssman** [comment]
RTSP uses UDP, not TCP. So I'm afraid not.

**Comment by Nidheeshv0312** [comment]
rtsp can work over both tcp and udp

**Comment by Nidheeshv0312** [comment]
is  there any point in  which i can do a flle dumo of the video stream

**Comment by CendioOssman** [comment]
websockify can store the traffic, but it's a custom format only really meant for debugging and tests. So I'm afraid you can't get any generally useful files, no.
