### ISSUE TITLE
specify a application port

### ISSUE THREAD

**Issue by Nidheeshv0312** [novnc/websockify#484]
i have a live555 based streamer application, i will start the live555 rtsp server application, it will create a port and push data to that port.
How can i use the run command to sepcify the port of the streamer

These are my logs , Instead of going to 8551(streamer port) its is going to another port 37545
WebSocket server settings:
  - Listen on :8552
  - No SSL/TLS support (no cert file)
  - proxying from :8552 to './H264orH265VideoStreamer' (port 37545)
Starting './H264orH265VideoStreamer'
streamr is 264 and stream 0
streaming "stream.h264"
Play pri stream using the URL "rtsp://192.168.1.24:8551/pri"
Beginning streaming...
192.168.1.24 - - [01/Jun/2021 10:36:02] 192.168.1.24: Plain non-SSL (ws://) WebSocket connection
192.168.1.24 - - [01/Jun/2021 10:36:02] connecting to command: './H264orH265VideoStreamer' (port 37545)

**Comment by CendioOssman** [comment]
If you want to proxy to a port rather than a command then you should specify a target host and port. E.g. `localhost:8551` in your case. Please see the output of `--help` for the different options.
