### ISSUE TITLE
Cannot connect through https

### ISSUE THREAD

**Issue by masrurakif62** [novnc/websockify#490]
Hello,

I currently have a setup running noVNC on a Raspberry Pi that's connected to a port running TightVNC on a separate laptop. I can connect to the noVNC (http://<ip-address>:<listen-port>:vnc.html) and access the VNC-server normally but I can't connect to it if I'm on a different network or when I enter https instead of http. I am running websockify as a daemon process.

This is what I've done so far:

sudo apt install novnc
sudo apt install websockify

cd /etc/ssl/
sudo openssl req -x509 -nodes -newkey rsa:2048 -keyout novnc.pem -out novnc.pem -days 365

cd ~
sudo websockify -D --web=/usr/share/novnc/ --cert=/etc/ssl/self.pem <listen-port> <ip-address>:<port>

My goal is to be able to connect to the noVNC from any network through a https link, so I want to know if I setup the websockify correctly. If not, what should I do?

**Comment by masrurakif62** [comment]
Just an update, I mixed up the names for my SSL certificate so the daemon service couldn't detect the certificate. I am able to connect through a https link but I am still unable to connect to it from a different network.

**Comment by CendioOssman** [comment]
I see you've also written to our discussion group, so let's avoid duplication and discuss everything over there.
