### ISSUE TITLE
Custom Plugin for reading token from mysql database

### ISSUE THREAD

**Issue by tiziano-pedrazzoli** [novnc/websockify#491]
is there a possibility to create a plugin to read the tokens (essentially the vnc server port) from a mysql database so you don't have to manually update a text file? The wiki doesn't explain very well how to build a custom plugin.

**Comment by CendioOssman** [comment]
I'm afraid that's the only documentation we have. I suggest you have a look at the existing plugins and work from that. And fetching tokens from a mysql database should work just fine.
