### ISSUE TITLE
Please provide an example of how to use with Flask and flask-sockets

### ISSUE THREAD

**Issue by nmz787** [novnc/websockify#492]
I have a website written in Flask, and would like to embed noVNC. I first came here from noVNC's repo, but wasn't able to wrap my head completely around how I could spawn websockify, and pass it the websocket object from the flask-socket handler. So I started trying to write my own proxy using Threads... but it's not working too well and I've been studying the RFB protocol for the last hour or two and hacking away without much progress.

Would it be possible to create an example script showing off websockify/noVNC using flask and flask-sockets?
https://github.com/heroku-python/flask-sockets/

**Comment by CendioOssman** [comment]
I see you've also written to our discussion group, so let's continue there to avoid duplication.

**Comment by nmz787-intel** [comment]
can you provide a URL to the discussion group?

**Comment by samhed** [comment]
https://groups.google.com/forum/?fromgroups#!forum/novnc
