### ISSUE TITLE
Can I proxy Tcp and websockify at the same time?

### ISSUE THREAD

**Issue by ziqingkeshi** [novnc/websockify#496]
Hello, 
I have a problem now, I need to proxy noVNC, and for some reasons, I cannot use proxy tools such as Nginx, so I chose a springboot proxy project smiley-http-proxy-servlet, and then I When proxying, I found a ws://127.0.0.1:8888/websockify request. Can I proxy tcp and websockify at the same time?
 If you can help me, I will be very grateful.

**Comment by ziqingkeshi** [comment]
@CendioOssman

**Comment by CendioOssman** [comment]
I'm afraid we don't have any expertise in how to configure various proxies. You'll have to ask your question in those projects and hopefully they can help you out with the correct configuration.
