### ISSUE TITLE
What version is my websockify?

### ISSUE THREAD

**Issue by mteam88** [novnc/websockify#499]
I need a simple way to check what version of websockify I have installed at usr/bin/websockify. I am using a buster raspberry pi 3 from a terminal.

**Comment by CendioOssman** [comment]
I'm afraid we don't embed the version number in websockify, so you'll need to check with whatever system was used to install it. E.g. dpkg. If you are using the version included with Debian Buster then that seems to be 0.8.0, which is extremely ancient.
