### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by ayoub-tl** [novnc/websockify#500]
installation failed when trying to install
sudo python setup.py install
![image](https://user-images.githubusercontent.com/68382823/144233994-ea749732-a1ad-4853-a0f8-7328870eeea3.png)

**Comment by manics** [comment]
https://github.com/novnc/websockify#installing-websockify
Try python3

**Comment by CendioOssman** [comment]
Indeed. Python 2 is no longer supported, I'm afraid.
