### ISSUE TITLE
Support the feature that proxies the TCP traffic to the websocket traffic

### ISSUE THREAD

**Issue by andrey-apporto** [novnc/websockify#505]
Hi everyone.
Thanks very much for this great project.
I'd like to know whether this project supports the proxy/bridge from the TCP traffic to the websocket traffic.

Thanks.

**Comment by CendioOssman** [comment]
Ehm... Yes? That's what we have in the project description:

> Websockify is a WebSocket to TCP proxy/bridge. This allows a browser to connect to any application/server/service. 

Or am I misunderstanding the question?
