### ISSUE TITLE
SSL target with self-signed certificate

### ISSUE THREAD

**Issue by Yanis-F** [novnc/websockify#506]
## Context
I am trying to build a web version of an application I am making, so I am using secured WebSockets instead of secured socket.
I want to use WebSockify to make my new web-version client use my current app server.

The catch is: I use a self-signed certificate for my app server, and I'm pretty sure this causes the forwarding not to work.

## Command

```
websockify localhost:3000 localhost:3001 
    --ssl-target
    --ssl-only
    --cert=/path/to/Certificate.pem
    --key=/path/to/Certificate.key 
    -v
```
where `/path/to/Certificate.{pem,key}` are the self-signed pem certificate and the corresponding private key I use **for my app server**.

## Error logs
```
/usr/lib/python3.10/site-packages/websockify/websocket.py:31: UserWarning: no 'numpy' module, HyBi protocol will be slower
  warnings.warn("no 'numpy' module, HyBi protocol will be slower")
WebSocket server settings:
  - Listen on localhost:3000
  - SSL/TLS support
  - Deny non-SSL/TLS connections
  - proxying from localhost:3000 to localhost:3001 (using SSL)

127.0.0.1: new handler Process
handler exception: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:997)
exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/websockify/websockifyserver.py", line 662, in top_new_client
    client = self.do_handshake(startsock, address)
  File "/usr/lib/python3.10/site-packages/websockify/websockifyserver.py", line 565, in do_handshake
    retsock = context.wrap_socket(
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:997)
127.0.0.1: new handler Process
127.0.0.1 - - [15/Feb/2022 14:21:36] "GET / HTTP/1.1" 101 -
127.0.0.1 - - [15/Feb/2022 14:21:36] 127.0.0.1: SSL/TLS (wss://) WebSocket connection
127.0.0.1 - - [15/Feb/2022 14:21:36] connecting to: localhost:3001 (using SSL)
```

## Question
Note that I did accept the self-signed certificate of the WebSockify server I connect to in my browser. The problems seems to come from the fact that the WebSockify client I connect to my app server does not trust my app server's self-signed certificate.

How can I make WebSockify forward sockets to a server using a self-signed SSL certificate ?
or What did I miss ?

**Comment by CendioOssman** [comment]
I'm afraid we don't currently support any options for that TLS connection so it will be locked to the system defaults.

For now I would suggest setting up your own CA (it's fairly easy to do with OpenSSL), and use that instead of self-signed certs. You can then add that CA to the system trust on your websockify machine.

**Comment by Yanis-F** [comment]
I did create a `ca.pem`, that I added to my system's trust and used it to issue `server.pem`, which replaced the certificate I was using.

`openssl verify server.pem` outputs `server.pem: OK`
I manually add the certificate on my browser by trying to connect to https://localhost:3000 and manually click "proceed anyway"

**But I still get the exact same error.**

Do I have any way of finding out which SSL/TLS connection is failing? (between my browser and WebSockify as a server, or between WebSockify as a client and my server).

The error is logged before the `127.0.0.1 - - [15/Feb/2022 14:21:36] connecting to: localhost:3001 (using SSL)`, I would assume it comes from the connection between the browser and WebSockify as a server.
However, I know my server uses TLS1.2, so maybe the fact that it tries connecting to it using SSL (even if I specify `--ssl-version=tlsv1_2`), and seeing "SSLV3" in the error, I'm thinking maybe the error comes from the fact that WebSockify as a client to my server tries to initiate a connection using SSL3 while my server expects TLS1.2?

Is there a way to find out which connection does the error comes from (Browser -> WebSockify  or  WebSockify -> My server)?

I'm running out of ideas about what the error could be caused by 


# formalities:
## Command

```
websockify localhost:3000 localhost:3001
 --ssl-target
 --ssl-only
 --cert=/path/to/server.pem
  --key=/path/to/server.key \
 --ssl-version=tlsv1_2
 --log-file=./websockify.log
 -v
```
## Output
```
/usr/lib/python3.10/site-packages/websockify/websocket.py:31: UserWarning: no 'numpy' module, HyBi protocol will be slower
  warnings.warn("no 'numpy' module, HyBi protocol will be slower")
WebSocket server settings:
  - Listen on localhost:3000
  - SSL/TLS support
  - Deny non-SSL/TLS connections
  - proxying from localhost:3000 to localhost:3001 (using SSL)
127.0.0.1: new handler Process
handler exception: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:997)
exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/websockify/websockifyserver.py", line 662, in top_new_client
    client = self.do_handshake(startsock, address)
  File "/usr/lib/python3.10/site-packages/websockify/websockifyserver.py", line 565, in do_handshake
    retsock = context.wrap_socket(
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:997)
127.0.0.1: new handler Process
127.0.0.1 - - [22/Feb/2022 17:07:24] "GET / HTTP/1.1" 101 -
127.0.0.1 - - [22/Feb/2022 17:07:24] 127.0.0.1: SSL/TLS (wss://) WebSocket connection
127.0.0.1 - - [22/Feb/2022 17:07:24] connecting to: localhost:3001 (using SSL)
127.0.0.1 - - [22/Feb/2022 17:07:27] localhost:3001: Client closed connection
E|2022-02-22 16:07:27.71 Dispatch error  : 8 127.0.0.1 SSL read failure             <<<< This is my server's log
127.0.0.1 - - [22/Feb/2022 17:07:27] localhost:3001: Closed target
^CIn exit
Closing socket listening at localhost:3000
```

**Comment by Yanis-F** [comment]
I'm closing that temporarily, I just figured out an issue on my end - these ssl error may have nothing to do with WebSockify.
I will reopen the issue if I still get issues after fixing my things~

**Comment by VivianoRiccardo** [comment]
same issue
