### ISSUE TITLE
inetd support appears broken

### ISSUE THREAD

**Issue by computerquip-work** [novnc/websockify#510]
There were numerous issues preventing me from using this functionality:
* There's no documentation on how to use this mode so if I'm just using it incorrectly, please let me know.
* It cannot wrap over applications in this mode. To avoid this, I made separate inetd daemons which works fine. Maybe that's for the best.
* If you do try to wrap over a separate inetd daemon, it tries to hook rebind.so into the program which should be unnecessary.
* With python 3.6.9, it gets stuck in an infinite loop printing `handler exception: [Errno 22] Invalid argument`.
* With 3.10.4, I get `OSError: [Errno 88] Socket operation on non-socket`. This appears to be caused by calls like this `socket.fromfd(sys.stdin.fileno(), socket.AF_INET, socket.SOCK_STREAM)`. See https://github.com/python/cpython/issues/83866

**Comment by CendioOssman** [comment]
Yeah, inetd mode is not something I think is tested that often. Could you share how you've tried to set it up and I can see if I can reproduce the issues here?

**Comment by computerquip-work** [comment]
My use is something like this:
```
x11vnc -rfbport 5910 &
tcpserver 0.0.0.0 6900 websockify --inetd --run-once 127.0.0.1:5910
```
then I just try to connect 6900 with NoVNC. tcpserver is from [here](http://cr.yp.to/ucspi-tcp.html). For Ubuntu, it's part of the [ucspi-tcp](https://packages.ubuntu.com/ucspi-tcp) package. Any of them should do the same (such as s6-tcpserver). Just be warned that this will cause the `handler exception: [Errno 22] Invalid argument` infinite loop problem.

I can't reliably reproduce the `OSError: [Errno 88] Socket operation on non-socket` problem, so I'm a bit confused on the circumstances I was getting that error.

**Comment by CendioOssman** [comment]
I had a look at the code, and it is expected that we get a listening socket in inetd mode. I.e. inetd should be configured in the `wait` mode. It looks like `tcpserver` doesn't support this mode from what I can tell.

So if you use a regular inetd and make sure `wait` is enabled, then everything should work fine.
