### ISSUE TITLE
Data loss while transmitting large amounts of data

### ISSUE THREAD

**Issue by msnatepg** [novnc/websockify#513]
I think this is related to or at least very similar to #63 and #36.

We've discovered an issue when transmitting large amounts of data (in our case from target to client).

When the target completed the transmission of the data, it can happen that the target closes the connection while websockify still has data in the client-side buffer.
Then, websockify closes also the client-side connection, which leads to a loss of data.

We see in a packet capture that websockify receives all of the data, but not all of the data is written to the websocket.
The last message in the websocket is "Target closed".

We've debugged further and realized that the moment websockify closes the client connection len(cqueue) is != 0, so there's still data in the client-side buffer which has to be sent.

I assume that this is unwanted behavior.

We've implemented a workaround by checking if there's still data in the buffer before closing the client-side socket.

While I'm unsure if there are any side-effects of doing this, it seems to solve our problem.

            if target in ins:
                # Receive target data, encode it and queue for client
                buf = target.recv(self.buffer_size)
                if len(buf) == 0 and len(cqueue) == 0:
                    if self.verbose:
                        self.log_message("%s:%s: Target closed connection",
                                self.server.target_host, self.server.target_port)
                    raise self.CClose(1000, "Target closed")

                if len(buf) != 0:
                    cqueue.append(buf)
                    self.print_traffic("{")

**Comment by CendioOssman** [comment]
Indeed. Flushing in both directions seem to be missing. Your code will work, but it will spend 100% whilst flushing as it will constantly be notified that the target socket is active. A proper fix needs to ignore the target socket once it has signalled closure.
