### ISSUE TITLE
websockify issue multiple user control one vnc server

### ISSUE THREAD

**Issue by king-dragon** [novnc/websockify#522]
i am doing research on websockify but i am facing a problem i want multiple users to access my vnc independently but when i use the command

```
websockify -D \
     --web /usr/share/novnc/ \
     --cert /etc/ssl/novnc.pem\
     6081 \
     localhost:5901 \
     2>/dev/null
```
And accessing novnc from 2 different browsers to control vnc, it's like the same machine controlling 1 screen, is there any help when I access novnc from different machines they work independently?

After 2 days of researching, I think I can use token to do this but I don't know how to use websockify token can you help me

**Comment by CendioOssman** [comment]
Have you checked the wiki page about using tokens?

It's found here:

https://github.com/novnc/websockify/wiki/Token-based-target-selection

**Comment by king-dragon** [comment]
> I'm afraid you're mixing up sections. Please only look under the **TokenFile Plugin** heading and the example there. The **Custom Plugins** heading is for advanced usage where you write your own code. This assumes a familiarity with programming and is not for most users.

but i don't have target.config.d file

**Comment by CendioOssman** [comment]
That is something you'll have to create. websockify is not preconfigured for any tokens.

**Comment by king-dragon** [comment]
> That is something you'll have to create. websockify is not preconfigured for any tokens.

 is my targt.config.d correct?

// my targt.config.d
U6F7msdQ: 127.0.0.1:5900
1oJw2DwG: 127.0.0.1:5901

**Comment by CendioOssman** [comment]
Yes, that looks correct. Normally `target.config.d` will be a directory with multiple files, but it's also okay to just point directly towards a single file.
