### ISSUE TITLE
Q: How to provide target user/pw ?

### ISSUE THREAD

**Issue by Z3TA** [novnc/websockify#523]
The target is a Mac that requires username and password.

When trying to connect via websockify from noVNC I get "Authentication failure" but no login prompt.

How do I provide the username and password for the Mac ?

I'm also running -v for verbose, but websockify doesn't output anything ...

Have tried:

`websockify my-ip:5900 macbook-ip:5900 -v --auth-source user:pass --auth-plugin BasePlugin`

and with --auth-plugin BasicHTTPAuth I get "Failed to connect to server" in noVNC.

**Comment by Z3TA** [comment]
On the Mac's Sharing settings i clicked Computer Settings.,.. and checked "VNC viewers may control screen with password" ... That got me one step further...

**Comment by CendioOssman** [comment]
This is really a noVNC question, as it is noVNC that handles all authentication. websockify is just a dumb proxy and has no idea what protocol is used.

noVNC only recently got support for Apple's more advanced authentication, so you'll need to wait for the next release of noVNC or check out a development version from git. At that point, you should get a prompt for username and password.
