### ISSUE TITLE
No file is being created while recording the session

### ISSUE THREAD

**Issue by AithaTarun** [novnc/websockify#526]
When I am using the commands:

$ bash run 6080 vnc_host --record "path to store recording" --web "noVNC path"
(or)
$ bash novnc_proxy --vnc vnc_host --listen 6080 --record "path to store recording"

to connect to a VNC server and record the session, I am able to connect to the server, but the session is not recording (the file is not getting created).

Update: The file is being created when we open vnc_lite.html, but not working with vnc.html

Could anyone please find a solution for this.

**Comment by AithaTarun** [comment]
![1](https://user-images.githubusercontent.com/67645139/190112268-7669d5b6-2c6f-4d8e-ab9e-684b33a1c5c1.png)

**Comment by CendioOssman** [comment]
So that is indeed bypassing websockify in some manner as you've started websockify on port 6080, not 8080.

Is the hostname the host where websockify runs? If not, then that also needs to be changed.

**Comment by AithaTarun** [comment]
Ok thanks, it worked, I have changed WebSocket host to local machine

**Comment by CendioOssman** [comment]
Great! Glad to hear it. I'll go ahead and close this issue then.
