### ISSUE TITLE
Cannot use letsencrypt cert and key following the directions here

### ISSUE THREAD

**Issue by gwhizoftv** [novnc/websockify#533]
HI All,

After installing noVNC and NGINX on my Debian 11 tiger VNCserver, I created a cert and key using certbot.
These are issued by Let'sEncrypt. I tried invoking websockify this way:

`
root@....:# websockify -D     --web /usr/share/novnc/     6080     localhost:5901 --cert /etc/letsencrypt/csr/0000_csr-certbot.pem --key /etc/letsencrypt/keys/0000_key-certbot.pem
`

When connecting from the noVNC client using Chrome on MacOS Monterey, the Chrome browser console shows:

`
WebSocket connection to 'wss://<fqdn>:5901/novnc/websockify' failed: 
open @ websock.js:210
_connect @ rfb.js:403
_updateConnectionState @ rfb.js:648
rfb.js:688 Failed when connecting: Connection closed (code: 1006)
_fail @ rfb.js:688
(anonymous) @ rfb.js:222
(anonymous) @ websock.js:225
`

We need the benefits of a real cert, not a self signed one.

**Comment by CendioOssman** [comment]
This  seems to be Python websockify, not websockify-js, so I'm moving the issue there.

You also have at least two discussions going on in the groups concerning this, so I'm going to close this issue in favour of those.
