### ISSUE TITLE
wrap mode needs better explanation and examples in the README

### ISSUE THREAD

**Issue by gwhizoftv** [novnc/websockify#535]
Hi All,

Wrap mode seems like it might be useful for starting the vncserver and automatically assigning the vncserver port. Our documentation refers to a program called ./run. What is ./run? and who is invoking it? When and how are they invoking it?

**Comment by CendioOssman** [comment]
It's in the root folder of the project, hence `./`. Just copy and paste the examples. It's not more complicated than that.

Note that you need to run `make` first, though, which unfortunately isn't mentioned. websockify will tell you to do so though, if you try to use wrap without the support library.
