### ISSUE TITLE
Multiple instances or token-based selection?

### ISSUE THREAD

**Issue by per-samuelsson** [novnc/websockify#538]
To proxy for more backends than one, what are pros/cons using token-based selection of backend vs running multiple instances of websockify? Resource-usage?

**Comment by CendioOssman** [comment]
I don't think that was a concern. It was more about having a single port/service handling multiple users. Some tokens are also based on external authentication.

So if all you want is easy access to multiple sessions, then feel free to deploy whatever works best for you.
