### ISSUE TITLE
how to replay the frame buffer data

### ISSUE THREAD

**Issue by gaoxiong523** [novnc/websockify#543]
![image](https://user-images.githubusercontent.com/34258160/204419741-e98f8319-1a17-4bbe-80f0-db1754c9e7ba.png)
sorry , i want to know how to replay the raw frame data use javascript. please help me. Thanks.

**Comment by CendioOssman** [comment]
The only consumer of that data is this debugging tool in noVNC:

https://github.com/novnc/noVNC/blob/master/tests/playback.js

Please have a look at that code for an example of how to use the data.
