### ISSUE TITLE
container run multimple websockify progress，I hope run only one websockify progress。

### ISSUE THREAD

**Issue by fengsam6** [novnc/websockify#545]
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/24472985/208409702-662e42ee-00d6-480b-be42-f3c8f05e90b6.png">
容器websockify每次，每次容器vnc断开，重连，会启动一个新的websockify，会占用一些内存，希望容器启动一个websockify一个进程。

**Comment by CendioOssman** [comment]
I'm afraid that is how websockify is designed to handle many connections efficiently. It will fork off a child process for each connection.
