### ISSUE TITLE
Installing websockify fails due to not finding cffi_modules or setuptools_rust on raspios lite. 

### ISSUE THREAD

**Issue by techmaticsnz** [novnc/websockify#547]
These are the errors I am getting from installing websockify. This is an urgent request as websockify is part of the functional system we've built for video streaming. 

`UserWarning: Unknown distribution option: 'cffi_modules'`
`ModuleNotFoundError: No module named 'setuptools_rust'`

Any help would be appreciated. just learning to use websockify. 

Intending on setting up a different python apart from system python to see if we can fix the problem.

**Comment by techmaticsnz** [comment]
Found a workaround. Indeed installing python3.11 fixed the issue. Was able to build websockify.

**Comment by CendioOssman** [comment]
Neither of those things are something that's referenced from websockify, so there must have been something odd with Python on that system. I'm glad you were able to find a fix for it.
