### ISSUE TITLE
about target-config

### ISSUE THREAD

**Issue by shmily0000** [novnc/websockify#551]
"I put websockify and novnc in one pod, vncserver in another pod, and target specifies a file. When 127.0.0.1 is written in the file, it takes effect.". The IP address changed to pod will not take effect.

The content of the token.conf file:

root: 127.0.0.1:5901

How do I change this to an IP class for a pod? I will use multiple POs to place multiple VNC servers, but websockify is converted in a single pod

**Comment by CendioOssman** [comment]
I'm afraid that I'm not sure what you are referring to when you mention "pods". Red Hat's podman?

Unfortunately, your issue sounds like some network infrastructure problem. You should specify the IP address of the VNC server in that token file. If that doesn't work, then there is something in the network setup that needs to be adjusted. I'm afraid that is not something we have the expertise to help you with. I suggest you ask in a forum for the platform you are using.
