### ISSUE TITLE
Logging and monitor

### ISSUE THREAD

**Issue by FulvioSpelta** [novnc/websockify#553]
Hi all, I kindly ask if is it possibile to have a log in a standard format in order import it in monitoring systems.

More generally, how do you monitor the health and the usage of websockify in production environment ?

Just some info about my installation: I'm using websockify with the "TokenFile" plugin so i'd like to have a dashboard or, at least, a report about the connections that has been done and so on.

Thanks for any hint.

**Comment by CendioOssman** [comment]
websockify does not have a structured log format, no. And that's probably just the tip of the ice berg. I'm afraid websockify is not designed with production usage in mind, so it lacks many things for that use case.

Its target usage is prototyping and testing/development. So it's mostly a big pile of various features that people have found useful.
