### ISSUE TITLE
novnc session getting disconnected after 30 min if left idle

### ISSUE THREAD

**Issue by amule0317** [novnc/websockify#562]
I am using novnc websockify library to connect vnc console. I am able to connect to the console, but console get disconnected after 30 min if it is left idle (i.e no input is provided to console)

While debugging the websockify, below is the analysis,

When do_proxy(websockify/websocketproxy.py) method is called 

```
if cqueue or c_pend: wlist.append(self.request)
try:
    ins, outs, excepts = select.select(rlist, wlist, [], 1)
except (select.error, OSError):
    exc = sys.exc_info()[1]
```

For 30 min it return ins, outs, excepts as empty list.
2023-09-16 07:07:03.816 3843 INFO websockify.websocketproxy [req-********] Value of ins is []
2023-09-16 07:07:03.816 3843 INFO websockify.websocketproxy [req-********] Value of outs is []

After 30 min, we recieve below ins and outs
2023-09-16 07:07:04.631 3843 INFO websockify.websocketproxy [req-********] Value of ins is [<websockify.websockifyserver.CompatibleWebSocket object at 0x7fad0042a2e0>]
2023-09-16 07:07:04.631 3843 INFO websockify.websocketproxy [req-********] Value of outs is []
and then console get disconnected.

we analyzed that do_proxy method calls recv_frames(websockify/websockifyserver.py) method which internally call _recv_frames(websockify/websocket.py)

```
def _recv_frames(self):
# Fetches more data and decodes the frames
if not self._recv():
        if self.close_code is None:
            self.close_code = 1006
            self.close_reason = "Connection closed abnormally"
            self._sent_close = self._received_close = True
        self._close()
        return False
```

This calls self._recv() 

    def _recv(self):
        # Fetches more data from the socket to the buffer
        assert self.socket is not None

        while True:
            try:
                **data = self.socket.recv(4096)**
            except (socket.error, OSError):
                exc = sys.exc_info()[1]
                if hasattr(exc, 'errno'):
                    err = exc.errno
                else:
                    err = exc[0]

                if err == errno.EWOULDBLOCK:
                    raise WebSocketWantReadError

                raise

            if len(data) == 0:
                return False

Here after 30 min value of data is coming as None and it then returns false. and then it raise 1006 error.

Any idea, How the session is getting disconnected after 30 min.

**Comment by CendioOssman** [comment]
It sounds like you have a firewall or something killing connections if they are idle.

What does the browser console on the client say?

**Comment by amule0317** [comment]
<img width="1199" alt="Screenshot 2023-02-10 at 10 20 15 PM (1)" src="https://github.com/novnc/websockify/assets/59175307/373a6110-5627-408a-88a1-d2d2a2069125">

We are seeing this error
Server Disconnected (Code : 1006)

**Comment by CendioOssman** [comment]
We need to see the details from the Javascript console. The browsers unfortunately don't tell us enough that we can present in the UI.

**Comment by CendioOssman** [comment]
Thanks.

Not many more details there, but we can see that it wasn't initiated from noVNC at least. And since the browser didn't log anything extra, I would assume it was network initiated.

So unfortunately, it's not something we can really help you with. There is something on your network killing those connections. Likely a proxy or firewall. You'll need to figure out it is and get someone to adjust it to not kill these connections.
