### ISSUE TITLE
Server disconnected (code: 1015). Open developer tools (F12/Ctrl+Shift+I on Windows, Option+Command+I on Mac OS) and switch to "Console" for details

### ISSUE THREAD

**Issue by zhiduopc** [novnc/websockify#563]
Server disconnected (code: 1015/1006).
Open developer tools (F12/Ctrl+Shift+I on Windows, Option+Command+I on Mac OS) and switch to "Console" for details，websockify WSS keeps failing to connect, how do I configure this certificate and how do I issue a certificate to an IP?NoVNC keeps failing to connect!

**Comment by CendioOssman** [comment]
The only certificate documentation we have is this:

https://github.com/novnc/websockify/wiki/Encrypted-Connections

Unfortunately, it doesn't cover how to issue certificates for IP addresses. You'll need to search for some other guide for that. There should hopefully be some available on the web.
