### ISSUE TITLE
how to connect to tls vnc server

### ISSUE THREAD

**Issue by bmagistro** [novnc/websockify#565]
Is it possible for websoockify to leverage the `--ssl-target` option and connect to a ssl enabled vnc server, in this case libvirt/qemu?  The target is using ssl certs that are trusted by the system (corporate ca loaded).  As of now I was trying to do this in conjunction with theforeman (https://github.com/theforeman/foreman) so it's possible that additional arguments need to be added.  When running with `-v` and/or `--log-file` I didn't see any additional output to help debug the connection.  If it is necessary to stand up a standalone novnc + websockify to debug that should be possible as well.

**Comment by CendioOssman** [comment]
No, not the type of TLS that is used in QEMU. websockify doesn't understand the VNC protocol, so it can only add TLS if the entire stream is wrapped in it. That is not the case for most of the TLS extensions to VNC.

With the current design, that functionality would need to be added to noVNC. And it is very unlikely that will ever be added, as the browser's TLS stack is not available from JavaScript.

An alternative would be a different WebSocket proxy that can handle the VNC protocol and do some transparent adjustments of the communication to add TLS. I'm not aware of any existing such proxies, though.

**Comment by bmagistro** [comment]
thanks for the quick reply and understand/mostly expected on all points.  I did see the questions/comments about novnc not supporting tls and wasn't sure if it was just a tunnel/wrapper on the qemu side...one can hope.

trying to explore some other options, can websockify listen on a range of ports?  so for example if we put an instance on the libvirt/qemu hosts that listened on the range we allow from libvirt (5900:5910 for this example), a connection in on 5902 would go out 5902 or would we need an instance per?  i'm also assuming in that scenario websockify could talk to websockify as a ssl target.

**Comment by CendioOssman** [comment]
websockify cannot listen to multiple ports, no. You'd need multiple instances in that case. There is the token system, for multiplexing to multiple servers using a single port.

You should not have one websockify connect to a second websockify as that will mean you'll get WebSocket traffic stacked upon another layer of WebSocket traffic. noVNC is not prepared to deal with that.

**Comment by bmagistro** [comment]
thanks again for the quick reply, we'll have to keep thinking on this.
