### ISSUE TITLE
Websockify: Integrate xterm.js

### ISSUE THREAD

**Issue by merkys7** [novnc/websockify#572]
Hello,
I was wondering, does anybody had any success with integrating xterm.js with Websockify?
I really love Websockify but just the novnc client is a bit less convenient than xterm.js

**Comment by CendioOssman** [comment]
websockify is just a proxy. noVNC is not integrated in any way, even if it is websockify's primary user. So integrating any other front-end application would be out of the scope of the project.

xterm.js also doesn't look like it has any network support. So it is not something that can be used together with websockify. You'd need to look for something like an ssh client written in JavaScript. I'm afraid I don't have any specific suggestions for you there.
