### ISSUE TITLE
add support for accept-ranges in http server

### ISSUE THREAD

**Issue by realies** [novnc/websockify#573]

**Comment by samhed** [comment]
Websockify bundles an extremely simple web server for testing purposes, we probably won't add more features to it. It isn't intended for production environments and is not recommended for anyone to use in a real setup.

**Comment by realies** [comment]
What's the recommended approach for a real setup?

**Comment by samhed** [comment]
Use a proper web server like apache, and configure that to meet your needs.

**Comment by realies** [comment]
do you mean reverse proxying it to websockify?

**Comment by CendioOssman** [comment]
Yes. Or ideally, if there is a WebSocket proxy that is more production ready than websockify. I'm afraid I'm not aware of any, though. :/

What we do here is take the core WebSocket code from websockify and integrate it in to our own web server code that has the features we need.
