### ISSUE TITLE
websockify: error: too many arguments

### ISSUE THREAD

**Issue by kevin-niland** [novnc/websockify#578]
I am trying to run the following command:

`websockify -D --web /usr/share/novnc/ --cert /home/user/vnc_out.pem --key /home/user/vnc_key.pem --token-plugin TokenFile --token-source /home/user/tokens 6080 localhost:5910`

However, I get the following message when I try to:

```
Usage: 
    websockify [options] [source_addr:]source_port [target_addr:target_port]
    websockify [options] [source_addr:]source_port -- WRAP_COMMAND_LINE

websockify: error: Too many arguments
```

I saw in one of the files, I think the one that starts websockify that if there are more than two arguments beginning with `--` then it will throw this error. However, people have provided examples of using websockify with more than two arguments such as here: https://github.com/novnc/noVNC/issues/522

Am I running this wrong? For context, I am trying to achieve an implementation that doesn't require the user to enter their vnc password when visiting the appropriate link (using my example, `localhost:6080/vnc.html`) - will the command I am trying to run achieve this?

**Comment by kevin-niland** [comment]
@CendioOssman Can you give me an example of how I could run the above command? I am installing websockify 0.11.0 via pip (I can see there are more possible options now and an update usage output. This is how I am trying to use the command:

`websockify -D --web /usr/share/novnc/ 6080 localhost:5910 -- --cert /home/enmadm/vnc_out.pem --key /home/enmadm/vnc_key.pem --token-plugin TokenFile --token-source /home/enmadm/tokens`

However, I still get the following:

```
Usage: 
    websockify [options] [source_addr:]source_port [target_addr:target_port]
    websockify [options] --token-plugin=CLASS [source_addr:]source_port
    websockify [options] --unix-target=FILE [source_addr:]source_port
    websockify [options] [source_addr:]source_port -- WRAP_COMMAND_LINE

websockify: error: Too many arguments

```

**Comment by CendioOssman** [comment]
Drop `localhost:5910` from the list of arguments, and it should start up properly.
