### ISSUE TITLE
redirect based on params 

### ISSUE THREAD

**Issue by pociej** [novnc/websockify#587]
Hi, 

Maybe my question shows that I missed something important how websockify works but is there and option to create generic proxy, that redirect target is taken from request params? Currently i have api like that : 

```
docker run -it --rm -p 7000:80 novnc/websockify 80 10.1.1.1:5902
```

let say I need to redirect some requests to `10.1.1.1:5902` and others to `11.2.2.20:5902`. Is there a way to configure websokify so i can add some extra data to request to port `80` based on which proxy will redirect me to desired endpoint?

**Comment by CendioOssman** [comment]
We have the token system for that purpose. Please have a look here for how that can be used:

https://github.com/novnc/websockify/wiki/Token-based-target-selection

There are more token types than documented there. You'll need to check the code for the others, unfortunately.

**Comment by pociej** [comment]
@CendioOssman  thx that clarifies me a lot. Have one more question, could you please get me near the subject of exact security issues you guys mention in document saying "Allowing websockify connections to select arbitrary host and port targets is a large security issue and will not be supported by websockify".

**Comment by CendioOssman** [comment]
It would allow websockify to be an open proxy that could do malicious things. E.g. reach an internal network unrestricted, or perform attacks on other sites with the websockify owner looking like the perpetrator.
