### ISSUE TITLE
Mixing Windows and Python 3.3

### ISSUE THREAD

**Issue by jmcintyre** [novnc/websockify#66]
I have had websockify running on Windows against Python 3.2 for some time now. I've begun testing against Python 3.3 and have run into an issue. When a websocket connection is made, I receive the following error:

self = load(from_parent)
"Python\lib\multiprocessing\forking.py", line 344, in main
File "<string>", line 1, in <module>

Has anyone else tried running against Python 3.3 in Windows?

**Comment by CendioOssman** [comment]
This is a duplicate of #67, where multiprocessing and Windows don't mix well.
