### ISSUE TITLE
Problem with novnc-websockify on Windows

### ISSUE THREAD

**Issue by doriwal** [novnc/websockify#67]
1- I download the https://github.com/downloads/kanaka/websockify/Websockify%20Windows%20Service.zip

2- i unzip the folder at C:\Websockify Windows Service

3- i download https://github.com/downloads/kanaka/websockify/websockify.zip

and unzip and copy its content to C:\Websockify Windows Service

4- i download novnc from https://github.com/kanaka/noVNC

5- i unzip it at  C:\Users\waldman\Downloads\noVNC-master\noVNC-master

6- i run the command 

C:\Websockify Windows Service>websockify.exe --web "C:\Users\waldman\Downloads\noVNC-master\noVNC-master" 6080 localhost
:5901

the log is : 

WARNING: no 'resource' module, daemonizing support disabled
WebSocket server settings:
- Listen on :6080
- Flash security policy server
- Web server. Web root: C:\Users\waldman\Downloads\noVNC-master\noVNC-master
- No SSL/TLS support (no cert file)
- proxying from :6080 to localhost:5901

In my browser i am going to 

http://localhost:6080/vnc_auto.html?host=localhost&port=6080&true_color=1

also tried with 

http://localhost:6080/vnc_auto.html?host=localhost&port=5901&true_color=1

I am getting server disconnected --> WHY ? ? ? 

The server is fine as when i am trying to use 

http://kanaka.github.com/noVNC/noVNC/vnc_auto.html?host=localhost&port=5901&true_color=1

I can login to my server with no problem

So my question is What is missing in order that i will be able to use my novnc service and not to use the "http://kanaka.github.com/noVNC/noVNC/vnc_auto.html" 

I want to have my nonvc and not use external "kanaka.github.com" 

Thanks for help 

B.T.W same issue happened both at  windows & linux (I prefer windows solution) 

the log is 

  2: 127.0.0.1: ignoring socket not ready
  3: 127.0.0.1: ignoring empty handshake
  4: 127.0.0.1: "GET /auto.vnc.html?host=localhost&port=6080&true_color=1 HTTP/1.1" 404 -
  5: 127.0.0.1: ignoring socket not ready
  6: 127.0.0.1: "GET /auto-vnc.html?host=localhost&port=6080&true_color=1 HTTP/1.1" 404 -
  9: 127.0.0.1: ignoring socket not ready
 10: 127.0.0.1: ignoring empty handshake
 12: 127.0.0.1: ignoring socket not ready
 13: 127.0.0.1: ignoring empty handshake
 14: 127.0.0.1: ignoring empty handshake
 15: 127.0.0.1: ignoring empty handshake
 16: 127.0.0.1: ignoring empty handshake
 17: 127.0.0.1: ignoring empty handshake
 18: 127.0.0.1: ignoring empty handshake
 19: 127.0.0.1: ignoring empty handshake
 20: 127.0.0.1: ignoring empty handshake
 21: 127.0.0.1: ignoring empty handshake
 22: 127.0.0.1: ignoring empty handshake
 23: 127.0.0.1: ignoring empty handshake
 24: 127.0.0.1: ignoring empty handshake
 25: 127.0.0.1: ignoring empty handshake
 26: 127.0.0.1: ignoring empty handshake
 27: 127.0.0.1: ignoring empty handshake
 28: 127.0.0.1: ignoring empty handshake
 29: 127.0.0.1: ignoring empty handshake
 30: 127.0.0.1: ignoring empty handshake
 31: 127.0.0.1: ignoring empty handshake
 33: 127.0.0.1: ignoring socket not ready
 34: 127.0.0.1: ignoring empty handshake
 35: 127.0.0.1: ignoring empty handshake
 36: 127.0.0.1: ignoring empty handshake

**Comment by kabilraj1979** [comment]
@kanaka : I am trying to run the websockify on Windows 2012 R2 Standard (64 bit).
I have installed Python 2.7.11 version.
Installed compatible 64 bit versions of "py2exe" and "numpy".
Went through all of the issues mentioned for running novnc on Windows (especially #108 and #233)

Issue : When I try to connect via the web url (http://localhost/vnc.html?host=localhost&port=6080), I am getting handler exception : "can't pickle thread.lock objects"
"Import error: No module named run" from the forking.py

Please suggest a resolution. I get a feeling that there has not been robust successful running experience of this tool in Windows. Please let me know if it is not intended to run on Windows. Or am I missing something from my side? Appreciate your response

![image](https://cloud.githubusercontent.com/assets/29137048/26711123/e7665bd2-477b-11e7-9b83-ac5be90379ab.png)

![image](https://cloud.githubusercontent.com/assets/29137048/26711144/066c2e8a-477c-11e7-9a1e-c0f1bedf1a1a.png)

**Comment by kanaka** [comment]
@kabilraj1979 websockify does not work on Windows using python 2.X. There has been some success using python 3.X. However, the node.js version of websockify apparently (I don't have a Windows system to test with) works pretty well on Windows so I suggest you use the node.js version if it that is an option for you.

**Comment by kabilraj1979** [comment]
@kanaka : Thanks for your response. I believe you are referring to https://github.com/novnc/websockify/blob/master/other/js/websockify.js
Looks like it is doing websocket client request handling. How do I use it with the noVNC UI to get the tartget machine's desktop streamed? Can you point to any step-by-step method if you have a wiki? Or can you please create one so that for interested people, it will be easy to follow?

**Comment by kabilraj1979** [comment]
@kanaka : Thanks for the response. The websockify.js allowed me to connect. Thanks. Need to explore what code is there in the web content. The js file was more or less doing the send and receive part of the web socket connection (kind of a reverse proxy)?

**Comment by sonicnkt** [comment]
Is there a way to build the nodejs version in a simple script/exe version that is easy to deploy? 
I saw the Powershell script here: https://github.com/aberbegall/novnc-launch-powershell/blob/master/README.md
But it has a lot of dependencies (installing full nodejs, then download additional packages etc), so there is no way to easily deploy this for me on multiple clients. 
My goal was to put together a free, open and independent remote solution that wont rely on any additional servers.

**Comment by kabilraj1979** [comment]
@kanaka: Every time I have to proxy to a VNC server, I need to have different instances of the websockify.js. Is there a way to run it as a listener that can allow multiple connections on the fly? WebSocketConnections can be opened from one instance of the websockify.js on the fly right?

**Comment by kanaka** [comment]
@kabilraj1979 multiple clients can connect to the same instance of websockify.js at the same time. However, you need to have one instance of websockify.js per target that you want to connect to. The python version of websockify supports target plugins which allow the target to be selected by an opaque token provided by the client. However, this functionality has not been ported to the websockify.js yet.

**Comment by CendioOssman** [comment]
I tested the SIGCHLD thing, but as you've noticed there are a lot of issues remaining with `multiprocessing`. For now I've put an active block in the code so it refuses to start on Windows. Should make our handling of issues a bit smoother at least.

**Comment by gdan101** [comment]
@sonicnkt: I managed to create an exe (from the Node.js version) so you don't need to install Node.js and the components.
These are the steps (I never used Node.js before, so I am pretty sure there is a shorter solution):

1. Install NodeJS (the default global installation path is: %AppData%\npm, %AppData%\npm-cache)

2. Install required components, run:
	- npm install -g express
	- npm install -g optimist
	- npm install -g policyfile
	- npm install -g ws
	- npm install -g http-server
	- npm install -g mime-types
	- npm install -g pkg

3. Create a folder named "websockify" under "%AppData%\npm\node_modules\" and copy the contents of folder "websockify\other\js" in it.

4. Run (documentation of arguments -> https://www.npmjs.com/package/pkg): pkg "%AppData%\npm\node_modules\websockify\websockify.js" --targets "latest-win-x86,latest-win-x64" --out-path "your output folder"

**Comment by samhed** [comment]
That works well for me too. Tested on Windows 10 and with noVNC + TigerVNC Windows server.

**Comment by mliudev** [comment]
@gdan101 Could you tell me what version of node you had when you got this to run? I'm running into an issue with nodejs 10.1.0 and websockify: https://github.com/novnc/websockify/issues/307#issuecomment-391125660

**Comment by gdan101** [comment]
@mliudev I had node-v6.11.4 on a Windows 7 x64 machine!

**Comment by SiddharthJyoti** [comment]
@kanaka Does NOVNC support Reverse VNC connection the way it is supported by tightvnc.
Reference: https://kempniu.wordpress.com/2009/03/21/reverse-connections-in-tightvnc/

How can we open novnc viewer in listening mode if answer is yes for above question.

We are using novnc to capture devices inside network however we want to use same web application for capturing(vnc) devices outside the network over the internet. This is because web server can not reach devices with private ip behind the router. We would like to use reverse vnc feature that should allow devices with private ip to share screen to novnc client on web server

**Comment by samhed** [comment]
@SiddharthJyoti Please stop spamming the same question in mutliple places

**Comment by SiddharthJyoti** [comment]
@samhed Your prompt response on the question would be appreciated.

**Comment by samhed** [comment]
noVNC does not support reverse connections like the one described in that blog.
